
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoViz module
#' @description Initialize ExpoViz module analysis. It can generate an R6 class object
#'     integrating all the analysis information.
#' @usage InitViz()
#' @details ExpoViz module is designed for the data visualization of different
#'     statistical and biological analyses in a user friendly and easy way, including
#'     four typical classes of visualization.
#' @return An R6 class object.
#' @export
#' @examples res <- InitViz()
#' @author Ning Gao, Bin Wang (corresponding author)

InitViz = function(){
  url = paste0(urlhead,'InitViz')
  library(gridExtra)
  ddpcr::quiet(library(GGally))
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Load data file for ExpoViz module
#' @description Load data for visualization.
#' @usage LoadViz(PID = res$PID, UseExample = "example#1")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param UseExample chr. Method of uploading data. If "default"，user should upload their own data files,
#'    or use "example#1" provided by this module.
#' @param ExdataPath chr. Input data file directory, e.g. "D:/test/eg_expoviz_data.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @param VodataPath chr. Input vocabulary file directory, e.g. "D:/test/eg_expoviz_voca.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @return An R6 class object containing the input data.
#' @export
#' @examples res = InitViz()
#'     res1 = LoadViz(PID = res$PID, UseExample = "example#1")
#'     res1 =  LoadViz(PID = res$PID,UseExample = "default",
#'     DataPath = "/Users/lanq/Desktop/test/eg_expoviz_data.xlsx",
#'     VocaPath = "/Users/lanq/Desktop/test/eg_expoviz_voca.xlsx")
#' @author Ning Gao, Bin Wang (corresponding author)

LoadViz =function(PID,
                  UseExample="default",
                  DataPath=NULL,
                  VocaPath=NULL){
  url = paste0(urlhead,'LoadViz')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)
    vodata = readxl::read_excel(VocaPath)
  }else{
    exdata = NULL
    vodata = NULL}
  if(length(DataPath) == 0){
    DataPath = ""
  }
  if(length(VocaPath) == 0){
    VocaPath = ""
  }
  res = httr::POST(url,
                   body = serialize(list(PID=PID,
                                         UseExample=UseExample,
                                         Expodata=exdata,
                                         Vocadata=vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Plot category dot
#' @description Visualize data via dot plot.
#' @usage VizCateDot(PID=res$PID,OutPath="default",Group="F",Vars="X4,X5,X6,X7,X8,X9,X10",Parameter="mean",Brightness="light",Palette="default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param Group lgl.Whether to separate dataset into train and test datasets for d
#'     ata imputation,including T or F.The default option is F.
#' @param Vars chr. Specifying the variables.
#'     Available options include:
#'     "all.x", all independent variables;
#'     "all.c", all covariate variables;
#'     "all.cx", combination of All x and All x;
#'     or input a character string specifying the variables,separated by comma "," without space(e.g."X4,X5,X6,X7,X8,X9,X10").
#'     No more than 50 variables be entered is recommended (< 50 variables).
#' @param Parameter chr. Specifying which parameter of the data to be the ordinate of
#'     the output plot. Available options include: "mean", "median", "min", "max", "mad"
#'     or "sd".Default is "mean".
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and "Journal". The "Journal" option provides several journal preference styles
#'    including cell, nature, science, lancet, nejm, and jama.
#' @details The dot plot is used to display the relative position of
#'     two data points in the same time period, or compare the difference
#'     between the two categorical variables.
#' @return A list containing one or three plots.
#'     When Group=T,
#'     (1) "all_light_default1": the whole dataset visualization result;
#'     (2) "train_light_default1": the train dataset visualization result;
#'     (3) "test_light_default1": the test dataset visualization result.
#'     When Group=F,
#'     (1) "light_default1": the whole dataset visualization result.
#' @export
#' @examples res = InitViz()
#'     res1 = LoadViz(PID = res$PID, UseExample = "example#1")
#'     res2 = VizCateDot(PID=res$PID,OutPath="default",Group="F",Vars="X4,X5,X6,X7,X8,X9,X10",Parameter="mean",Brightness="light",Palette="default1")
#' @author Ning Gao,Bin Wang(corresponding author)

VizCateDot = function(PID,
                      OutPath="default",
                      Group="F",
                      Vars,
                      Parameter="mean",
                      Brightness="light",
                      Palette='default1'){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizCate_Dot')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizCate_DotGroup=Group,
                               VizCate_DotVars=Vars,
                               VizCate_DotParameter=Parameter,
                               VizCate_DotBrightness=Brightness,
                               VizCate_DotPalette=Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/Cate'))
  for (name in names(results$Cate_Dot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/Cate/',Parameter,'_',name,".png"),
                      plot = results$Cate_Dot[[name]] ,
                      width =  results$Dot_plotpara$PlotWidth,
                      height = results$Dot_plotpara$PlotHeight,
                      units = "cm"),silent = TRUE
    )
  }
  return(results)
}


#' @title Plot relationship network
#' @description Visualize data via network plot.
#' @usage VizRelatNetwork(PID=res$PID,OutPath="default",VarsY="Y2",VarsC="all.x",VarsX="all.c",Family="gaussian",Layout="force-directed",CutOff=0.8,Brightness="light",Palette="default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory. e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsY chr. Specifying the dependent variables(e.g."Y2").
#' @param VarsC chr. Specifying the covariate variable.Available options include:
#'     "all.c", all covariate variables;
#'     or input a character string specifying the variables,separated by comma "," without space(e.g."C1,C2").
#' @param VarsX chr. Specifying the independent variables.Available options include:
#'     "all.x", all independent variables;
#'     or input a character string specifying the variables,separated by comma "," without space(e.g."X4,X5,X6,X7,X8,X9,X10").
#' @param Family chr. Specifying the data distribution in order to determine the visualization method.
#'      Available options include:"gaussian","poisson" and "logistic".Notice that the family are
#'     determined by data type of an outcome, or the plot can not be visualized.
#' @param Layout chr. Visualization layout. Available options include "force-directed" and "degree-circle".
#' @param CutOff num. Partial outcomes to visualize which is determined by correlation
#'     coefficient r. The range must between 0 and 1.
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and "Journal". The "Journal" option provides several journal preference styles
#'    including cell, nature, science, lancet, nejm, and jama.
#' @details The network plot is used to visualize the relationship between
#'     the input variables by using ggraph package.
#' @return A list containing one plot.
#'     (1) "light_default1": the visualization result;
#' @export
#' @examples #res = InitViz()
#'     #res1 = LoadViz(PID = res$PID, UseExample = "example#1")
#'     #res2 = VizRelatNetwork(PID=res$PID,OutPath="default",
#'     #VarsY="Y2",VarsC="all.x",VarsX="all.c",Family="gaussian",
#'     #Layout="force-directed",CutOff=0.8,Brightness="light",Palette="default1")
#' @author Ning Gao,Bin Wang(corresponding author)

VizRelatNetwork = function(PID,
                           OutPath="default",
                           VarsY,
                           VarsC="all.c",
                           VarsX="all.x",
                           Family="gaussian",
                           Layout="force-directed",
                           CutOff=0.8,
                           Brightness="light",
                           Palette="default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizRelat_Network')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizRelat_NetworkVarsY=VarsY,
                               VizRelat_NetworkVarsC=VarsC,
                               VizRelat_NetworkVarsX=VarsX,
                               VizRelat_NetworkFamily=Family,
                               VizRelat_NetworkLayout=Layout,
                               VizRelat_NetworkCutOff=CutOff,
                               VizRelat_NetworkBrightness=Brightness,
                               VizRelat_NetworkPalette=Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/Network'))
  for (name in names(results$Relat_Network)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/Network', "/network_",Layout,"_",
                             Brightness,"_",
                             Palette,".png"),
                      plot = results$Relat_Network[[name]],
                      width =  20,
                      height = 20,
                      units = "cm"),silent = TRUE
    )
  }
  return(results)
}


#' @title Plot elationship edge bundling
#' @description Visualize data via edge bundling plot.
#' @usage VizRelatEdgeBundling(PID=res$PID,OutPath="default",VarsY = "Y2",VarsX = "all.x",VarsC = "C2",Family = "gaussian" ,SizeFor = "pvalue",Brightness = "light",Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory. e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsY chr. Dependent variables for visualization(e.g."Y2").
#' @param VarsC chr. Covariate variable.Available options include:
#'     "all.c", all covariate variables;
#'     or input a character string specifying the variables,separated by comma "," without space(e.g."C1,C2").
#' @param VarsX chr. Independent variables.Available options include:
#'     "all.x", all independent variables;
#'     or input a character string specifying the variables,separated by comma "," without space(e.g."X4,X5,X6,X7,X8,X9,X10").
#' @param Family chr. Specifying the data distribution in order to determine the visualization method.
#'      Available options include:"gaussian","poisson" and "logistic".Notice that the family are
#'     determined by data type of an outcome, or the plot can not be visualized.
#' @param SizeFor chr. Parameter to represent the size of the points in the output plot. Available options
#'     include "pvalue" and "beta".The default option is "pvalue".
#' @param CutOff num. Partial outcomes to  visualize which is determined by correlation coefficient r.
#'     The range must between 0 and 1.
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and "Journal". The "Journal" option provides several journal preference styles
#'    including cell, nature, science, lancet, nejm, and jama.
#' @details The edge bundling plot is used to bundle the edges closely
#'     in order to reduce complexity.
#' @return A list containing one plot.
#'     (1) "light_default1": the visualization result;
#' @export
#' @examples res = InitViz()
#'     res1 = LoadViz(PID = res$PID, UseExample = "example#1")
#'     res2 = VizRelatEdgeBundling(PID=res$PID,OutPath="default",VarsY = "Y2",
#'     VarsX = "all.x",VarsC = "C2",Family = "gaussian" ,SizeFor = "pvalue",
#'     Brightness = "light",Palette = "default1")
#' @author Ning Gao,Bin Wang(corresponding author)

VizRelatEdgeBundling = function(PID,
                                OutPath="default",
                                VarsY,
                                VarsC="all.c",
                                VarsX="all.x",
                                Family="gaussian",
                                SizeFor="pvalue",
                                Brightness="light",
                                Palette="default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizRelat_EdgeBundling')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizRelat_EdgeBundlingVarsY=VarsY,
                               VizRelat_EdgeBundlingVarsC =VarsC,
                               VizRelat_EdgeBundlingVarsX = VarsX,
                               VizRelat_EdgeBundlingFamily = Family,
                               VizRelat_EdgeBundlingSizeFor = SizeFor,
                               VizRelat_EdgeBundlingBrightness = Brightness,
                               VizRelat_EdgeBundlingPalette =Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/EdgeBundling'))
  for (name in names(results$Relat_EdgeBundling)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/EdgeBundling', "/EdgeBundling_",SizeFor,
                             "_",Brightness,"_",Palette,".png"),
                      plot = results$Relat_EdgeBundling[[name]],
                      width =  20,
                      height = 20,
                      units = "cm"),silent = TRUE
    )
  }
  return(results)
}


#' @title Plot relationship heatmep
#' @description Visualize data via heatmap plot.
#' @usage VizRelatHeatmap(PID=res$PID,OutPath="default",Group = "F",VarsY = "Y2",VarsX = "X1,X4,X5,X6,X7,X8,X9,X10",Method = "spearman",Brightness = "light",Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory. e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param Group lgl.Whether to separate dataset into train and test datasets for d
#'     ata imputation,including T or F.The default option is F.
#' @param VarsY chr. Dependent variables for visualization(e.g."Y2").
#' @param VarsX chr. Independent variables.Available options include:
#'     "all.x", all independent variables;
#'     or input a character string specifying the variables,separated by comma "," without space(e.g."X4,X5,X6,X7,X8,X9,X10").
#' @param Method chr. Method to calculate the correlation. Default option is "spearman".
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and "Journal". The "Journal" option provides several journal preference styles
#'    including cell, nature, science, lancet, nejm, and jama.
#' @details The heatmap plot is used to display data in color changes
#'     as a matrix.
#' @return A list containing one or two plots.
#'     When Group=T,
#'     (1) "train_light_default1": the train dataset visualization result;
#'     (2) "test_light_default1": the test dataset visualization result.
#'     When Group=F,
#'     (1) "light_default1": the whole dataset visualization result.
#' @export
#' @examples res = InitViz()
#'     res1 = LoadViz(PID = res$PID, UseExample = "example#1")
#'     res2 = VizRelatHeatmap(PID=res$PID,OutPath="default",Group = "F",
#'     VarsY = "Y2",VarsX = "X1,X4,X5,X6,X7,X8,X9,X10",Method = "spearman",
#'     Brightness = "light",Palette = "default1")
#' @author Ning Gao, Bin Wang (corresponding author)

VizRelatHeatmap = function(PID,
                           OutPath="default",
                           Group="F",
                           VarsY,
                           VarsX,
                           Method="spearman",
                           Brightness="light",
                           Palette="default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizRelat_Heatmap')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizRelat_HeatmapGroup=Group,
                               VizRelat_HeatmapVarsY=VarsY,
                               VizRelat_HeatmapVarsX=VarsX,
                               VizRelat_HeatmapMethod=Method,
                               VizRelat_HeatmapBrightness=Brightness,
                               VizRelat_HeatmapPalette=Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/Heatmap'))
  for (i in c(1:length(results$Relat_Heatmap))){
    try(
      ggplot2::ggsave(paste0(OutPath,'/Heatmap', "/Heatmap_",names(results$Relat_Heatmap)[i],"_",Method,".png"),
                      results$Relat_Heatmap[[i]] ,
                      width  =  results$Heatmap_para[[i*2-1]],
                      height  =  results$Heatmap_para[[i*2]],
                      limitsize = FALSE,
                      units = "cm"),silent = TRUE
    )
  }
  return(results)
}


#' @title Plot relationship matrix
#' @description Visualize data via matrix plot.
#' @usage VizRelatMatrix(PID=res$PID,OutPath="default",Group = "F",VarsY = "Y2",VarsX = "X4,X5,X6,X7,X8,X9,X10",Method = "spearman")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory. e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param Group lgl.Whether to separate dataset into train and test datasets for
#'     data imputation,including T or F.The default option is F.
#' @param VarsY chr. Dependent variables for visualization(e.g."Y2").
#' @param VarsX chr. Independent variables.Available options include:
#'     "all.x", all independent variables;
#'     or input a character string specifying the variables,separated by comma "," without space(e.g."X4,X5,X6,X7,X8,X9,X10").
#' @param Method chr. Method to calculate the correlation. Default option is "spearman".
#' @details The matrix plot is used to make a matrix of plots with a
#'     given data set.
#' @return A list containing one or two plots.
#'     When Group=T,
#'     (1) "train_light_default1": the train dataset visualization result;
#'     (2) "test_light_default1": the test dataset visualization result.
#'     When Group=F,
#'     (1) "light_default1": the whole dataset visualization result.
#' @export
#' @examples res = InitViz()
#'     res1 = LoadViz(PID = res$PID, UseExample = "example#1")
#'     res2 = VizRelatMatrix(PID=res$PID,OutPath="default",Group = "F",
#'     VarsY = "Y2",VarsX = "X4,X5,X6,X7,X8,X9,X10",Method = "spearman")
#' @author Ning Gao, Bin Wang (corresponding author)

VizRelatMatrix = function(PID,
                          OutPath="default",
                          Group="F",
                          VarsY,
                          VarsX,
                          Method="spearman"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizRelat_Matrix')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizRelat_MatrixGroup =Group,
                               VizRelat_MatrixVarsY =VarsY,
                               VizRelat_MatrixVarsX =VarsX,
                               VizRelat_MatrixMethod = Method
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/Matrix'))
  for (i in c(1:length(results$Relat_Matrix))){
    try(
      ddpcr::quiet(ggplot2::ggsave(paste0(OutPath,'/Matrix', "/Matrix_",names(results$Relat_Matrix)[i],"_",Method,".png"),
                      results$Relat_Matrix[[i]] ,
                      width  =  results$Relat_Matrix_para[[i*2-1]],
                      height  =  results$Relat_Matrix_para[[i*2]],
                      units = "cm")),silent = TRUE
    )
  }
  return(results)
}


#' @title Plot distribution sierra
#' @description Visualize data via sierra plot.
#' @usage VizDistrSierra(PID=res$PID,OutPath="default",Group = "F",Vars = "X14,X15,X16,X17,X18,X19,X20",Brightness = "light",Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory. e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param Group lgl.Whether to separate dataset into train and test datasets for
#'     data imputation,including T or F.The default option is F.
#' @param Vars chr. Variables to be visualized(e.g."X4,X5,X6,X7,X8,X9,X10").Available options include:
#'     "all.x", all independent variables;
#'     "all.c", all covariate variables;
#'     "all.cx", combination of all.x and all.c;
#'     or input a character string specifying the variables,separated by comma "," without space(e.g."X4,X5,X6,X7,X8,X9,X10").
#'     No more than 50 variables be entered is recommended (< 20 variables).
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and "Journal". The "Journal" option provides several journal preference styles
#'    including cell, nature, science, lancet, nejm, and jama.
#' @details The sierra plot is used to visualize the kernel density
#'     estimation of data.
#' @return A list containing one or three plots.
#'     When Group=T,
#'     (1) "all_light_default1": the whole dataset visualization result;
#'     (2) "train_light_default1": the train dataset visualization result;
#'     (3) "test_light_default1": the test dataset visualization result.
#'     When Group=F,
#'     (1) "light_default1": the whole dataset visualization result.
#' @export
#' @examples res = InitViz()
#'     res1 = LoadViz(PID = res$PID, UseExample = "example#1")
#'     res2 = VizDistrSierra(PID=res$PID,OutPath="default",Group = "F",
#'     Vars = "X14,X15,X16,X17,X18,X19,X20",Brightness = "light",
#'     Palette = "default1")
#' @author Ning Gao,Bin Wang(corresponding author)

VizDistrSierra = function(PID,
                          OutPath="default",
                          Group="F",
                          Vars,
                          Brightness="light",
                          Palette="default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizDistr_Sierra')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizDistr_SierraGroup=Group,
                               VizDistr_SierraVars=Vars,
                               VizDistr_SierraBrightness=Brightness,
                               VizDistr_SierraPalette=Palette),
                   encode = 'json')

  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/DistrSierra'))
  for (name in names(results$Sierra)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/DistrSierra/','Sierra_',name,".png"),
                      plot = results$Sierra[[name]] ,
                      width =  results$Sierra_para$PlotWidth,
                      height = results$Sierra_para$PlotHeight,
                      units = "cm"),silent = TRUE
    )
  }
  return(results)
}


#' @title Plot component dendrogram
#' @description Visualize data via dendrogram plot.
#' @usage VizCompoDendrogram(PID=res$PID,OutPath="default",Group = "T",Vars = "X4,X5,X6,X7,X8,X61,X66,X67,X200",Parameter = "median",DistMethod = "euclidean",ClusterMethod = "ward.D2",ClusterNum = "4",Brightness = "light",Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory. e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param Group lgl.Whether to separate dataset into train and test datasets for
#'     data imputation,including T or F.The default option is T.
#' @param Vars chr. Variables to be visualized(e.g."X4,X5,X6,X7,X8,X9,X10").Available options include:
#'     "all.x", all independent variables;
#'     "all.c", all covariate variables;
#'     "all.cx", combination of all.x and all.c;
#'     or input a character string specifying the variables,separated by comma "," without space(e.g."X4,X5,X6,X7,X8,X9,X10").
#' @param Parameter chr. Specifying which parameter of the data to be the ordinate of
#'     the output plot. Available options include: "mean", "median", "min", "max", "mad"
#'     or "sd".Default is "mean".
#' @param DistMethod chr.The distance measure. This must be one of "euclidean", "maximum"
#'     or "manhattan".Default is "euclidean".
#' @param ClusterMethod chr.The agglomeration method. This should be one of "ward.D",
#'     "ward.D2" or "single".Default is "ward.D".
#' @param ClusterNum num. The number of groups for cutting the tree.Default is 4.
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and "Journal". The "Journal" option provides several journal preference styles
#'    including cell, nature, science, lancet, nejm, and jama.
#' @details The dendrogram plot is used to plot beautiful dendrograms.
#' @return A list containing one or three plots.
#'     When Group=T,
#'     (1) "all_light_default1": the whole dataset visualization result;
#'     (2) "train_light_default1": the train dataset visualization result;
#'     (3) "test_light_default1": the test dataset visualization result.
#'     When Group=F,
#'     (1) "light_default1": the whole dataset visualization result.
#' @export
#' @examples res = InitViz()
#'     res1 = LoadViz(PID = res$PID, UseExample = "example#1")
#'     res2= VizCompoDendrogram(PID=res$PID,OutPath="default",Group = "T",
#'     Vars = "X4,X5,X6,X7,X8,X61,X66,X67,X200",Parameter = "median",
#'     DistMethod = "euclidean",ClusterMethod = "ward.D2",ClusterNum = "4",
#'     Brightness = "light",Palette = "default1")
#' @author Ning Gao,Bin Wang(corresponding author)

VizCompoDendrogram = function(PID,
                              OutPath="default",
                              Group="T",
                              Vars,
                              Parameter="median",
                              DistMethod="euclidean",
                              ClusterMethod="ward.D",
                              ClusterNum=4,
                              Brightness="light",
                              Palette="default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizCompo_Dendrogram')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizCompo_DendrogramGroup=Group,
                               VizCompo_DendrogramVars=Vars,
                               VizCompo_DendrogramParameter=Parameter,
                               VizCompo_DendrogramDistMethod=DistMethod,
                               VizCompo_DendrogramClusterMethod=ClusterMethod,
                               VizCompo_DendrogramClusterNum=ClusterNum,
                               VizCompo_DendrogramBrightness=Brightness,
                               VizCompo_DendrogramPalette=Palette),
                   encode = 'json')

  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/Dendrogram'))
  for (name in names(results$Dendrogram)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/Dendrogram/Dendrogram_',name,'_',
                             Parameter,'_',
                             DistMethod,'_',
                             ClusterMethod,'_',name,".png"),
                      plot = results$Dendrogram[[name]] ,
                      width =  results$Dendrogram_para$PlotWidth,
                      height = results$Dendrogram_para$PlotHeight,
                      units = "cm"),silent = TRUE
    )
  }
  return(results)
}

#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by InitViz
#' @export
#' @examples res = InitViz()
#'    res1 = LoadViz(PID = res$PID,UseExample = "example#1")
#'    res2 = VizCateDot(PID=res$PID,OutPath = "default",Group = "F",
#'    Vars = "X4,X5,X6,X7,X8,X9,X10",Parameter = "mean",
#'    Brightness = "light",Palette = "default1")
#'    FuncExit(PID = res$PID)
#' @author Ning Gao,Bin Wang(corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}
