
urlhead = 'http://www.exposomex.cn:8080/'

test_connect = function(){
  url = paste0(urlhead,'health')
  res = httr::GET(url)
  httr::content(res)
  return(res$status_code)
}

res = test_connect()
 

#' @title Initialize ExpoTidy module
#' @description Initialize ExpoTidy module analysis. It can generate an R6 class object. 
#' @usage InitTidy()
#' @param 
#' @details It is designed to tidy the data for the target model analysis.
#' @return An R6 class object.
#' @export res = InitTidy()
#'    res
#'    FuncExit(PID = res$PID)
#' @examples res <- InitTidy()
#' @author Bin Wang

InitTidy = function(){
  url = paste0(urlhead,'InitTidy')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}

#' @title Load data file for ExpoTidy module
#' @description Load data file for ExpoCros module
#' @usage LoadTidy(PID, UseExample = "default", DataPath=NULL, VocaPath=NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoCros
#' @param UseExample chr. Method of uploading data. If "default"，user should upload their own data files, 
#'    or use "example#1" provided by this module. 
#' @param DataPath chr. Input directory of data file, e.g. "D:/test/eg_data_biolink.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @param VocaPath chr. Input directory of vocabulary file, e.g. "D:/test/eg_voca_biolink.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @details 
#' @return An R6 class object containing the input data.
#' @export
#' @examples res <- InitTidy()
#'    res = LoadTidy(PID = res$PID, UseExample = "example#1")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang

LoadTidy =function(PID,
                   UseExample = "default",
                   DataPath = NULL,
                   VocaPath = NULL){
  url = paste0(urlhead,'LoadTidy')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)
    vodata = readxl::read_excel(VocaPath)
  }else{
    exdata = NULL
    vodata = NULL}
  
  res = httr::POST(url,
                   body = serialize(list(PID = PID,
                                         UseExample = UseExample,
                                         Expodata = exdata,
                                         Vocadata = vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Missing data imputation.
#' @description Missing data imputation.
#' @usage TransImput(PID,OutPath = "default",Group,Vars,Method)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Group lgl. Whether to separate dataset into train and test data for processing data.
#' @param Vars Variables to be imputed. Available options include: 
#'     "all.x", all exposure variables; "all.c", all covariates; 
#'     "all.cx", combination of All X and All C. Users can also choose available variables 
#'     by selecting "Other" option, and copy the variables by clicking "Available vars". 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @param Method Methods used for imputation. Available options include "lod" or "cart" methods. 
#'     For "lod" method, limit of detection (LOD) should be included in the "Vocabulary" file.
#' @details 
#' @return An R6 class object containing variable(s) with imputation.
#' @export
#' @examples res = InitTidy()
#'     res1 = LoadTidy(PID=res$PID, UseExample="example#1")
#'     res1$Expo$Data
#'     res2 = TransImput(PID=res$PID, Group="T", Vars="all.x", Method="lod")
#'     res2$Expo$Data
#'     FuncExit(PID = res$PID)
#' @author Bin Wang

TransImput =function(PID,
                     OutPath = "default",
                     Group,
                     Vars,
                     Method){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransImput')
  res = httr::POST(url,
                   body = list(PID=PID,
                               TransImputGroup=Group,
                               TransImputVars=Vars,
                               TransImputMethod=Method),
                   encode = 'json')
  results = unserialize(httr::content(res))
  
  dir.create(paste0(OutPath,'/TransImput'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                       paste0(OutPath,'/TransImput/Expo_Data.csv'),
                       delim = ","),silent = TRUE
      )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransImput/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )
  
  return(results$eSet)
}


#' @title Delete variables with low variance
#' @description Whether to delete variables with low variance. The default option is "yes". 
#'     If skipped, it may result in failure to build models.
#' @usage DelNearZeroVar(PID, OutPath = "default")
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @details 
#' @return An R6 class object containing the variable(s) with acceptable variance.
#' @export
#' @examples res = InitTidy()
#'     res1 = LoadTidy(PID=res$PID, UseExample="example#1")
#'     res1$Expo$Data
#'     res2 = DelNearZeroVar(PID=res$PID)
#'     res2$Expo$Data
#'     FuncExit(PID = res$PID)
#' @author Bin Wang

DelNearZeroVar = function(PID,
                          OutPath = "default"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'DelLowVar')
  res =  httr::POST(url,
                    body = list(PID=PID),
                    encode = 'json')
  results = unserialize(httr::content(res))
  
  dir.create(paste0(OutPath,'/DelLowVar'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/DelLowVar/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/DelLowVar/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )
  
  return(results$eSet)
}


#' @title Delete variables with missing values
#' @description Whether to delete missing variables with low variance. The default option is "yes". 
#'     If skipped, it may result in failure during modeling.
#' @usage DelMiss(PID, OutPath = "default")
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions. 
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @details 
#' @return An R6 class object containing the variable(s) without missing values.
#' @export
#' @examples res = InitTidy()
#'     res1 = LoadTidy(PID=res$PID, UseExample="example#1")
#'     res1$Expo$Data
#'     res2 = DelMiss(PID=res$PID)
#'     res2$Expo$Data
#'     FuncExit(PID = res$PID)
#' @author Bin Wang 

DelMiss = function(PID,
                   OutPath = "default"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url =paste0(urlhead,'DelMiss')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  
  dir.create(paste0(OutPath,'/DelMiss'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/DelMiss/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/DelMiss/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )
  
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Transform data type
#' @description Transform data type
#' @usage TransType(PID,OutPath = "default",Vars,To)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Vars Variables to be imputed. Available options include: 
#'     "all.x", all exposure variables; "all.c", all covariates; 
#'     "all.cx", combination of All X and All C. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @param To chr. Indicate the type of the chosen variables to be transformed into. 
#'     Available options include "integer", "numeric", "character", "factor", "logical", and "date".
#' @details 
#' @return An R6 class object containing the variable(s) after transforming data type.
#' @export
#' @examples res = InitTidy()
#'     res1 = LoadTidy(PID=res$PID, UseExample="example#1")
#'     res1$Expo$Data
#'     res2 = TransType(PID=res$PID, Vars = "X1,X2", To = "character")
#'     res2$Expo$Data
#'     FuncExit(PID = res$PID)
#' @author Bin Wang 

TransType = function(PID,
                     OutPath = "default",
                     Vars,
                     To){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransType')
  res = httr::POST(url,
                   body = list(PID=PID,
                               TransTypeVars=Vars,
                               TransTypeTo=To),
                   encode = 'json')
  
  dir.create(paste0(OutPath,'/TransType'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransType/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransType/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )
  
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Classify variables into various groups 
#' @description Classify variables into various groups
#' @usage TransClass(PID, OutPath = "default", Group, Vars, LevelTo)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Group lgl. Whether to separate dataset into train and test data for processing data.
#' @param Vars Variables to be imputed. Available options include: 
#'     "all.x", all exposure variables; "all.c", all covariates; 
#'     "all.cx", combination of All X and All C. Users can also choose available variables 
#'     by selecting "Other" option, and copy the variables by clicking "Available vars". 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @param LevelTo The number of levels to convert variables to.
#' @details 
#' @return An R6 class object containing the variable(s) after classifying data into various levels.
#' @export
#' @examples res = InitTidy()
#'     res1 = LoadTidy(PID=res$PID, UseExample="example#1")
#'     res1$Expo$Data
#'     res2 = TransClass(PID=res$PID, Group="F", Vars="X1", LevelTo="4")
#'     res2$Expo$Data
#'     FuncExit(PID = res$PID)
#' @author Bin Wang 

TransClass = function(PID,
                      OutPath = "default",
                      Group,
                      Vars,
                      LevelTo){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransClass')
  res = httr::POST(url,
                   body = list(PID=PID,
                               TransClassGroup=Group,
                               TransClassVars=Vars,
                               TransClassLevelTo=LevelTo),
                   encode = 'json')
  
  dir.create(paste0(OutPath,'/TransClass'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransClass/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransClass/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )
  
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Scale variables
#' @description Scale variables
#' @usage TransScale(PID,OutPath = "default",Group,Vars,Method,...)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Group lgl. T (or TRUE) and F (or FALSE). Whether to separate dataset into train and test data for processing data.
#' @param Vars Variables to be imputed. Available options include: 
#'     "all.x", all exposure variables; "all.c", all covariates;
#'     "all.cx", combination of All X and All C. Users can also choose available variables 
#'     by selecting "Other" option, and copy the variables by clicking "Available vars". 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @param Method chr. Scaling methods. Available options include "normal" and "range".
#' @param Direct chr. Direction to be transformed, Available options include "positive" and "negative".
#' @param RangeLow num. Lower limit for range method. 
#' @param RangeUpper num. Upper limit for range method. It should be greater than the lower limit.
#' @details 
#' @return An R6 class object containing the variable(s) after scaling data.
#' @export
#' @examples res = InitTidy()
#'     res1 = LoadTidy(PID=res$PID, UseExample="example#1")
#'     res1$Expo$Data
#'     res2 = TransScale(PID=res$PID, Group="T", Vars="all.x", Method="normal")
#'     res2$Expo$Data
#'     FuncExit(PID = res$PID)
#' @author Bin Wang 

TransScale = function(PID,
                      OutPath = "default",
                      Group = "T",
                      Vars,
                      Method = "normal",
                      Direct="positive",
                      RangeLow="0",
                      RangeUpper="1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransScale')
  res = httr::POST(url,
                   body = list(PID=PID,
                               TransScaleGroup=Group,
                               TransScaleVars=Vars,
                               TransScaleMethod=Method,
                               TransScaleDirect=Direct,
                               TransScaleRangeLow=RangeLow,
                               TransScaleRangeUpper=RangeUpper),
                   encode = 'json')
  results = unserialize(httr::content(res))
  
  dir.create(paste0(OutPath,'/TransScale'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransScale/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransScale/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )
  
  return(results$eSet)
}


#' @title Transform variable distribution
#' @description Transform variable distribution
#' @usage TransDistr(PID,OutPath = "default", Vars, Method)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Vars Variables to be imputed. Available options include: 
#'     "all.x", all exposure variables; "all.c", all covariates; 
#'     "all.cx", combination of All X and All C. Users can also choose available variables 
#'     by selecting "Other" option, and copy the variables by clicking "Available vars". 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @param Method 
#' @details 
#' @return An R6 class object containing the variable(s) after transforming distribution.
#' @export
#' @examples res = InitTidy()
#'     res1 = LoadTidy(PID=res$PID, UseExample="example#1")
#'     res1$Expo$Data
#'     res2 = TransDistr(PID=res$PID, Vars="X6,X7", Method="log10")
#'     res2$Expo$Data
#'     FuncExit(PID = res$PID)
#' @author Bin Wang 

TransDistr = function(PID,
                      OutPath = "default",
                      Vars,
                      Method){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransDistr')
  res = httr::POST(url,
                   body = list(PID=PID,
                               TransDistrVars=Vars,
                               TransDistrMethod=Method),
                   encode = 'json')
  
  dir.create(paste0(OutPath,'/TransDistr'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransDistr/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransDistr/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )
  
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Transform exposure groups
#' @description Transform exposure groups
#' @usage TransGroup = function(PID, Vars="default", ToGroup)
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Vars Variables to be imputed. Available options include: 
#'     "all.x", all exposure variables; "all.c", all covariates; 
#'     "all.cx", combination of All X and All C. Users can also choose available variables 
#'     by selecting "Other" option, and copy the variables by clicking "Available vars". 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3".
#' @param ToGroup chr. Label the group of the target variables. Four common used names 
#'     are recommended, including Exposure, Metabolome, Proteome, and Immunome. 
#'     Users can also label the groups as you like.
#' @details 
#' @return An R6 class object containing the variable(s) after grouping the variables.
#' @export
#' @examples res = InitTidy()
#'     res1 = LoadTidy(PID=res$PID, UseExample="example#1")
#'     res1$Expo$Data
#'     res2 = TransGroup(PID=res$PID, Vars="X4,X5", ToGroup = "G1")
#'     res2$Expo$Data
#'     FuncExit(PID = res$PID)
#' @author Bin Wang 

TransGroup = function(PID,
                      OutPath = "default",
                      Vars,
                      ToGroup){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransGroup')
  res = httr::POST(url,
                   body = list(PID=PID,
                               TransGroupVars=Vars,
                               TransGroupToGroup=ToGroup),
                   encode = 'json')
  results = unserialize(httr::content(res))
  
  dir.create(paste0(OutPath,'/TransGroup'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransGroup/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransGroup/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )
  
  return(results$eSet)
}


#' @title Transform factor variables into dummy ones
#' @description Transform factor variables into dummy ones
#' @usage TransDummy(PID, Vars="default")
#' @param PID chr. Program ID. It must be the same with the PID generated by initial functions.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param Vars chr. Variables to be transformed as dummy variables. It should be noted that 
#'     there is fixed format for the entering characters separated with comma and without space, 
#'     e.g., "X1,X2,X3". If "default", all the factor variables will be transformed into dummy ones. 
#'     These variables need to be transformed as factor ones in previous transform step 
#'     using TransType function.
#' @details 
#' @return An R6 class object containing the variable(s) after transforming the factor 
#'     variables into dummy ones.
#' @export
#' @examples res = InitTidy()
#'     res1 = LoadTidy(PID=res$PID, UseExample="example#1")
#'     res1$Expo$Data
#'     res2 = TransDummy(PID=res$PID, Vars="default")
#'     res2$Expo$Data
#'     FuncExit(PID = res$PID)
#' @author Bin Wang 

TransDummy = function(PID,
                      OutPath = "default",
                      Vars="default"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'TransDummy')
  res = httr::POST(url,
                   body = list(PID=PID,
                               TransDummyVars=Vars),
                   encode = 'json')
  results = unserialize(httr::content(res))
  
  dir.create(paste0(OutPath,'/TransDummy'))
  try(vroom::vroom_write(results$eSet$Expo$Data,
                         paste0(OutPath,'/TransDummy/Expo_Data.csv'),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$eSet$Expo$Voca,
                         paste0(OutPath,'/TransDummy/Expo_Voca.csv'),
                         delim = ","),silent = TRUE
  )
  
  return(results$eSet)
}


#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It should be the same with the PID generated by initial functions.
#' @details 
#' @return Exit status
#' @export
#' @examples res = InitTidy()
#'    res1 = LoadTidy(PID=res$PID, UseExample="example#1")
#'    res2 = DelNearZeroVar(PID=res$PID)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}

