
library(gridExtra)
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoCros module
#' @description Initialize ExpoCros module analysis. It can generate an R6 class object. 
#' @usage InitCros()
#' @param 
#' @details ExpoCros module was designed to analyze the cross-sectional data from 
#'     exposome-wide association study (EWAS). This data structure can be obtained 
#'     from the epidemiological designs of cross-section, case-control, and cohort.
#' @return An R6 class object.
#' @export
#' @examples res <- InitCros()
#'     FuncExit(PID = res$PID)
#' @author Bin Wang

InitCros = function(){
  url = paste0(urlhead,'InitCros')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}

#' @title Load data file for ExpoCros module
#' @description Load data file for ExpoCros module
#' @usage LoadCros(PID, UseExample = "default", DataPath=NULL, VocaPath=NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoCros
#' @param UseExample chr. Method of uploading data. If "default"，user should upload their own data files, 
#'    or use "example#1" provided by this module. 
#' @param DataPath chr. Input directory of data file, e.g. "D:/test/eg_data_expocros.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @param VocaPath chr. Input directory of vocabulary file, e.g. "D:/test/eg_voca_expocros.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @details 
#' @return An R6 class object containing the input data.
#' @export
#' @examples res <- InitCros()
#'    res1 = LoadCros(PID = res$PID, UseExample = "example#1")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang

LoadCros =function(PID,
                   UseExample = "default",
                   DataPath = NULL,
                   VocaPath = NULL){
  url = paste0(urlhead,'LoadCros')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)
    vodata = readxl::read_excel(VocaPath)
  }else{
    exdata = NULL
    vodata = NULL}
  
  res = httr::POST(url,
                   body = serialize(list(PID = PID,
                                         UseExample = UseExample,
                                         Expodata = exdata,
                                         Vocadata = vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Find covariates
#' @description Find covariates
#' @usage FindCovaCros = function(PID, OutPath = "default", VarsY, VarsC_Prior = "default", 
#'     VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoCros
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsC_Prior chr. Potential covariates needing further statistical test. 
#'     The default value is all covariate variables listed in the data file. 
#' @param VarsC_Fixed chr. Covariate variables fixed in the model by users.
#' @param Method chr. Methods for screening the covariates, including two options, 
#'     i.e. "single.factor" and "two.stage".
#' @param Thr num. Threshold of the P-value for screening the covariates. It is 
#'     ranging 0.05-0.25. The default value is 0.1. 
#' @details 
#' @return A list containing the selected covariates.
#' @export
#' @examples res <- InitCros()
#'    res1 = LoadCros(PID = res$PID, UseExample = "example#1")
#'    res11 = FindCovaCros(PID=res$PID, VarsY = "Y1", 
#'    VarsC_Prior = "default", VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang

FindCovaCros = function(PID,
                        OutPath = "default",
                        VarsY,
                        VarsC_Prior = "default",
                        VarsC_Fixed = NULL,
                        Method = "single.factor",
                        Thr = 0.1){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  if(length(VarsC_Fixed) == 0){
    VarsC_Fixed = ""
  }
  
  url = paste0(urlhead,'FindCovaCros')
  res = httr::POST(url,
                   body = list(ExpoCrosPID = PID,
                               FindCovaCrosVarsY = VarsY,
                               FindCovaCrosVarsC_Prior= VarsC_Prior,
                               FindCovaCrosVarsC_Fixed = VarsC_Fixed,
                               FindCovaCrosMethod = Method,
                               FindCovaCrosThr = Thr),
                   encode = 'json')
  results = unserialize(httr::content(res))
  
  dir.create(paste0(OutPath,'/CrosCova'))
  df = data.frame(results$Covariates)
  try(
    vroom::vroom_write(df,
                       paste0(OutPath,'/CrosCova/covariates.csv'),
                       delim = ","),
    silent = TRUE
  )
  
  return(results)
}



#' @title Association analysis
#' @description Association analysis for cross-sectional data
#' @usage CrosAsso = function(PID, OutPath = "default",EpiDesign = "cross.sectional",
#'     VarsY, VarsX = "all.cx",VarsN = "single.factor",VarsSel = F,VarsSelThr = 0.1,
#'     IncCova = T,Family,RepMsr = F,Corstr = "ar1")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoCros
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param EpiDesign chr. Epidemiological design of the study, including "cohort" "case.control" 
#'     and "cross.sectional". It doesn’t affect the modeling, but the format of the output file. 
#'     For the three designs, the effect values are usually indicated by RR (relative risk) of cohort, 
#'     OR (odds ratio) of case-control, and beta value of cross-sectional.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsX chr. Exposure variable used for modeling. The default option is 
#'     "all.x" (All exposure variables are included). Users can also choose available variables. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param VarsN chr. Choose the single factor or multiple factor model. 
#'     Available options include "single.factor" and "multiple.factor"
#' @param VarsSel lgl. T (or TRUE) and F (or FALSE). Whether to select the significant variable for the final model. 
#'     Available options.
#' @param VarsSelThr num. If "VarsSel" = T, provide the selection threshold 
#'     of the P-value. Three value can be chosen, i.e. 0.05, 0.1, and 0.2.
#' @param IncCova lgl. T (or TRUE) and F (or FALSE). Whether to include the covariate
#'     selected in the function "FindCovaCros"
#' @param Family chr. The link function for the regression model according the data type of outcomes, 
#'     including "gaussian" for continuous variable, "binomial" for binary variable, 
#'     and "poisson" for counting variable
#' @param RepMsr lgl.  T (or TRUE) and F (or FALSE). Whether existing repeated measurement of the subjects.
#'     Available options.
#' @param Corstr chr. If "RepMsr" = T, the generalized estimating equations (GEE) will be used. 
#'     For GEE, three correlation structure options are "exchangeable" "ar1" "unstructured".
#' @details 
#' @return A list containing the association analysis results.
#' @export
#' @examples res <- InitCros()
#'    res1 = LoadCros(PID = res$PID, UseExample = "example#1")
#'    res2 = CrosAsso(PID=res$PID, EpiDesign = "cohort", 
#'    VarsY = "Y1", VarsX = "X5,X6,X7,X8,X9,X10,X11", VarsN = "single.factor" , 
#'    VarsSel = F, VarsSelThr = 0.1, IncCova = T, Family = "gaussian", 
#'    RepMsr = F,Corstr = "ar1")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang

CrosAsso = function(PID,
                    OutPath = "default",
                    EpiDesign = "cross.sectional",
                    VarsY,
                    VarsX = "all.cx",
                    VarsN = "single.factor",
                    VarsSel = F,
                    VarsSelThr = 0.1,
                    IncCova = T,
                    Family,
                    RepMsr = F,
                    Corstr = "ar1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  message("It may take some time. Thanks for your patient waiting!")
  
  url = paste0(urlhead,'CrosAsso')
  res = httr::POST(url,
                   body = list(ExpoCrosPID = PID,
                               CrosAssoEpiDesign = EpiDesign,
                               CrosAssoVarsY = VarsY,
                               CrosAssoVarsX = VarsX,
                               CrosAssoVarsN = VarsN,
                               CrosAssoVarsSel = VarsSel,
                               CrosAssoVarsSelThr = VarsSelThr,
                               CrosAssoIncCova = IncCova,
                               CrosAssoFamily = Family,
                               CrosAssoRepMsr = RepMsr,
                               CrosAssoCorstr = Corstr),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/CrosAsso'))
  for (name in names(results$AssoTable)){
    try(
      vroom::vroom_write(results$AssoTable[[name]],
                         paste0(OutPath,'/CrosAsso/', name,".csv"),
                         delim = ","),
      silent = TRUE
    )
  }
  return(results$AssoTable)
}


#' @title Visualize association analysis
#' @description Visualize association analysis
#' @usage VizCrosAsso = function(PID, OutPath = "default",VarsN = "single.factor",
#'     Layout = "volcano",Brightness = "light",Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoCros
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsN chr. Choose the single factor or multiple factor model. 
#'     Available options include "single.factor" and "multiple.factor"
#' @param Layout chr. Visualization layout. Available options include "forest" and "volcano".
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".  
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., cell, nature, science, lancet, nejm, and jama). 
#' @details 
#' @return An R6 class object containing the results' plot.
#' @export
#' @examples res <- InitCros()
#'    res1 = LoadCros(PID = res$PID, UseExample = "example#1")
#'    res2 = CrosAsso(PID=res$PID, EpiDesign = "cohort", VarsY = "Y1", 
#'    VarsX = "X5,X6,X7,X8,X9,X10,X11", VarsN = "single.factor" , 
#'    VarsSel = F, VarsSelThr = 0.1, IncCova = T, Family = "gaussian", 
#'    RepMsr = F,Corstr = "ar1")
#'    res13 = VizCrosAsso(PID=res$PID,VarsN="single.factor", Layout = "forest",
#'    Brightness = "dark",Palette = "default1")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang

VizCrosAsso = function(PID,
                       OutPath = "default",
                       VarsN = "single.factor",
                       Layout = "volcano",
                       Brightness = "light",
                       Palette = "default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizCrosAsso')
  res = httr::POST(url,
                   body = list(ExpoCrosPID=PID,
                               VizCrosAssoVarsN = VarsN,
                               VizCrosAssoLayout = Layout,
                               VizCrosAssoBrightness = Brightness,
                               VizCrosAssoPalette = Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))

  for (name in names(results$AssoPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/CrosAsso/',name,".png"),
                      plot = results$AssoPlot[[name]],
                      width =  results$AssoPlot_para[[name]][['width']],
                      height = results$AssoPlot_para[[name]][['height']],
                      units = "cm",dpi = 300,
                      limitsize = FALSE),
      silent = TRUE
    )
  }
  return(results$AssoPlot)
}

#' @title Build prediction models
#' @description Build prediction models
#' @usage CrosPred = function(PID,OutPath = "default",VarsY,VarsX = "all.x",
#'     PredType = "response",VarsSel = "F",VarsSelThr = 0.1,IncCova = T,
#'     RsmpMethod = "cv",Folds = 5,Ratio = 0.667,Repeats = 5)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoCros
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsX chr. Exposure variable used for modeling. The default option is 
#'     "all.x" (All exposure variables are included). Users can also choose available variables. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param PredType chr. Prediction type of the outcome variable, including "response" 
#'     for the actual values and "prob" for outcome with binary variable.
#' @param VarsSel lgl. Whether to select the significant variable for the final model.
#'     Available options include T (or TRUE) and F (or FALSE).
#' @param VarsSelThr num. If "VarsSel" = T, provide the selection threshold of 
#'     the P-value. Three value can be chosen, i.e. 0.05, 0.1, and 0.2.
#' @param IncCova lgl. Whether to include the covariate selected in the function of "FindCovaCros".
#'     Available options include T (or TRUE) and F (or FALSE).
#' @param RsmpMethod chr. Four resampling methods options for internal validation, including 
#'     "cv" (i.e.,Cross validation) , "loo" (i.e., eave-one-out), "bootstrap", and "holdout".
#' @param Folds num. Folds of Cross-validation resampling. It is ranging 2-10. 
#' @param Ratio num. Ratio of Bootstrap resampling. It is ranging 0.4-0.9.
#' @param Repeats num. Number of Bootstrap resampling. It is ranging 2-20.
#' @details 
#' @return A list containing the prediction performance evaluation.
#' @export
#' @examples res <- InitCros()
#'    res1 = LoadCros(PID = res$PID, UseExample = "example#1")
#'    res2 = TransScale(PID=res$PID, Group="T", Vars="all.x", Method="normal")
#'    res3 = CrosPred(PID=res$PID, VarsY = "Y1", VarsX = "X5,X6,X7,X8,X9,X10,X11",
#'    PredType = "response",VarsSel = F,VarsSelThr = 0.1,IncCova = F,
#'    RsmpMethod = "cv" ,Folds = 5,Ratio = 0.667,Repeats = 5)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang

CrosPred = function(PID,
                    OutPath = "default",
                    VarsY,
                    VarsX = "all.x",
                    PredType = "response",
                    VarsSel = "F",
                    VarsSelThr = 0.1,
                    IncCova = T,
                    RsmpMethod = "cv",
                    Folds = 5,
                    Ratio = 0.667,
                    Repeats = 5){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  message("It may take some time. Thanks for your patient waiting!")
  
  url = paste0(urlhead,'CrosPred')
  res = httr::POST(url,
                   body = list(ExpoCrosPID = PID,
                               CrosPredVarsY = VarsY,
                               CrosPredVarsX = VarsX,
                               CrosPredPredType = PredType,
                               CrosPredVarsSel = VarsSel,
                               CrosPredVarsSelThr = VarsSelThr,
                               CrosPredIncCova = IncCova,
                               CrosPredRsmpMethod = RsmpMethod,
                               CrosPredFolds = Folds,
                               CrosPredRatio = Ratio,
                               CrosPredRepeats = Repeats),
                   encode = 'json',
                   httr::timeout(600))
  results = unserialize(httr::content(res))
  
  dir.create(paste0(OutPath,'/CrosPred'))
  for (name in names(results$PredTable)){
    try(
      vroom::vroom_write(results$PredTable[[name]],
                         paste0(OutPath,'/CrosPred/', name,".csv"),
                         delim = ","),
      silent = TRUE
    )
  }
  return(results$PredTable)
}


#' @title Visualize the prediction performance
#' @description Visualize the prediction performance
#' @usage VizCrosPred = function(PID,OutPath = "default",Layout = "bar",
#'     Brightness = "light",Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoCros
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set. 
#' @param Layout chr. Visualization layout. Available options include "bar" and "roc"
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".  
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., cell, nature, science, lancet, nejm, and jama). 
#' @details 
#' @return A list containing the results' plot.
#' @export
#' @examples res <- InitCros()
#'    res1 = LoadCros(PID = res$PID, UseExample = "example#1")
#'    res2 = TransScale(PID=res$PID, Group="T", Vars="all.x", Method="normal")
#'    res3 = CrosPred(PID=res$PID, VarsY = "Y1", VarsX = "X5,X6,X7,X8,X9,X10,X11",
#'    PredType = "response",VarsSel = F,VarsSelThr = 0.1,IncCova = F,
#'    RsmpMethod = "cv" ,Folds = 5,Ratio = 0.667,Repeats = 5)
#'    res4 = VizCrosPred(PID=res$PID, Layout = "bar", 
#'    Brightness = "light", Palette = "science")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang

VizCrosPred = function(PID,
                       OutPath = "default",
                       Layout = "bar",
                       Brightness = "light",
                       Palette = "default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  url = paste0(urlhead,'VizCrosPred')
  res = httr::POST(url,
                   body = list(ExpoCrosPID = PID,
                               VizCrosPredLayout = Layout,
                               VizCrosPredBrightness = Brightness,
                               VizCrosPredPalette = Palette
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))

  for (name in names(results$PredPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/CrosPred/', name, ".png"),
                      plot = results$PredPlot[[name]],
                      width = 25,
                      height = 14,
                      units = "cm",
                      dpi = 300),
      silent = TRUE
    )
  }
  
  return(results$PredPlot)
}


#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by any initial functions.
#' @details 
#' @return Exit status
#' @export
#' @examples res = InitCros()
#'    res1 = LoadtCros(PID = res$PID,UseExample = "example#1")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID = PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}

