
library(gridExtra)
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoPanel module
#' @description Initialize ExpoPanel module analysis. It can generate an R6 class object.
#' @usage InitPanel()
#' @param 
#' @details ExpoPanel module is designed to conduct the analysis of the panel data. 
#'     It mainly aims to evaluate the associations between exposure factors and the health outcome.
#' @return An R6 class object.
#' @export
#' @examples res <- InitPanel()
#' @author Bin Wang (corresponding author)

InitPanel = function(){
  url = paste0(urlhead,'InitPanel')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Load data file for ExpoPanel module
#' @description Load data file for ExpoPanel module
#' @usage LoadPanel(PID, UseExample = "default", DataPath=NULL, VocaPath=NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoPanel
#' @param UseExample chr. Method of uploading data. If "default"，user should upload their own data files, 
#'    or use "example#1" provided by this module. 
#' @param DataPath chr. Input directory of data file, e.g. "D:/test/eg_data_biolink.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @param VocaPath chr. Input directory of vocabulary file, e.g. "D:/test/eg_voca_biolink.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @details 
#' @return An R6 class object containing the input data.
#' @export
#' @examples res <- InitPanel()
#'    res = LoadPanel(PID = res$PID, UseExample = "example#1")
#' @author Bin Wang 

LoadPanel =function(PID,
                    UseExample = "default",
                    DataPath = NULL,
                    VocaPath = NULL){
  url = paste0(urlhead,'LoadPanel')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)

    vodata = readxl::read_excel(VocaPath)
  }else{
    exdata = NULL
    vodata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID = PID,
                                         UseExample = UseExample,
                                         Expodata = exdata,
                                         Vocadata = vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Find covariates
#' @description Find covariates
#' @usage FindCovaPanel = function(PID, OutPath = "default", VarsY, VarsC_Prior = "default", 
#'     VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoPanel 
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsC_Prior chr. Potential covariates needing further statistical test. 
#'     The default value is all covariate variables listed in the data file. 
#' @param VarsC_Fixed chr. Covariate variables fixed in the model by users.
#' @param Method chr. Methods for screening the covariates, including two options, 
#'     i.e. "single.factor" and "two.stage".
#' @param Thr num. Threshold of the P-value for screening the covariates. It is 
#'     ranging 0.05-0.25. The defaults value is 0.1. 
#' @details 
#' @return A list containing the selected covariates.
#' @export
#' @examples res <- InitPanel()
#'    res1 = LoadPanel(PID = res$PID, UseExample = "example#1")
#'    res2 = FindCovaPanel(PID=res$PID, OutPath = OutPath, VarsY = "Y1",
#'    VarsC_Prior = "default", VarsC_Fixed ="C1", Method = "single.factor", Thr = 0.1)
#' @author Bin Wang 

FindCovaPanel = function(PID,
                         OutPath = "default",
                         VarsY,
                         VarsC_Prior = "default",
                         VarsC_Fixed = NULL,
                         Method = "single.factor",
                         Thr = 0.1){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  if(length(VarsC_Fixed) == 0){
    VarsC_Fixed = ""
  }
  
  url = paste0(urlhead,'FindCovaPanel')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VarsY = VarsY,
                               VarsC_Prior = VarsC_Prior,
                               VarsC_Fixed = VarsC_Fixed,
                               Method = Method,
                               Thr = Thr),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/PanelCova'))
  df = data.frame(results$CovaPanel)
  try(
    vroom::vroom_write(df,
                       paste0(OutPath,'/PanelCova/covariates.csv'),
                       delim = ","),
    silent = TRUE
  )
  return(results)
}


#' @title Association analysis of panel data
#' @description Association analysis of panel data
#' @usage PanelAsso = function(PID, OutPath = "default", VarsY, VarsX, VarsN = "single.factor",
#'     VarsRandomIpt = "SubjectID", VarsRandomSlp = "none", IncCova = F)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoPanel 
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsX chr. Exposure variable used for modeling. The default option is 
#'     "all.x" (All exposure variables are included). Users can also choose available variables. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param VarsN chr. Choose the single factor or multiple factor model. 
#'     Available options include "single.factor" and "multiple.factor"
#' @param VarsRandomIpt chr. Random intercept variable for the linear mixed-effect model. 
#'     The default is "SubjectID". 
#' @param VarsRandomSlp chr. Random slope variable for the linear mixed-effect model. 
#'     The default is "none". It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param IncCova lgl. T (or TRUE) and F (or FALSE). Whether to include the covariate(s) 
#'     selected in the function "FindCovaPanel"
#' @details 
#' @return A list containing the association analysis results.
#' @export
#' @examples res <- InitPanel()
#'    res1 = LoadPanel(PID = res$PID, UseExample = "example#1")
#'    res2 = TransImput(PID=res$PID,Group="T",Vars="all.x",Method="lod")
#'    res3 = DelNearZeroVar(PID = res$PID)
#'    res4 = DelMiss(PID = res$PID)
#'    res5 = TransType(PID=res$PID,Vars="Y1",To="factor")
#'    res6 = TransScale(PID=res$PID,Group="T",Vars="all.x",Method="normal")
#'    res7 = TransDummy(PID=res$PID,Vars="default")
#'    res8 = PanelAsso(PID=res$PID, OutPath = OutPath, VarsY = "Y1", 
#'     VarsX = "X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12", VarsN = "single.factor",
#'     VarsRandomIpt = "SubjectID", VarsRandomSlp = "none", IncCova = "F")
#'    res9 = PanelAsso(PID=res$PID, OutPath = OutPath, VarsY = "Y1", 
#'     VarsX = "X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12", VarsN = "multiple.factor",
#'     VarsRandomIpt = "SubjectID", VarsRandomSlp = "none", IncCova = "F")
#' @author Bin Wang 

PanelAsso = function(PID,
                     OutPath = "default",
                     VarsY,
                     VarsX,
                     VarsN = "single.factor",
                     VarsRandomIpt = "SubjectID",
                     VarsRandomSlp = "none",
                     IncCova = F){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  message("It may take some time. Thanks for your patient waiting!")
  
  url = paste0(urlhead,'PanelAsso')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VarsY = VarsY,
                               VarsX = VarsX,
                               VarsN = VarsN,
                               VarsRandomIpt = VarsRandomIpt,
                               VarsRandomSlp = VarsRandomSlp,
                               IncCova = IncCova),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/PanelAsso'))
  for (name in names(results$AssoTable)){
    try(
      vroom::vroom_write(results$AssoTable[[name]],
                         paste0(OutPath,'/PanelAsso/', name,".csv"),
                         delim = ","),
      silent = TRUE
    )
  }
  return(results$AssoTable)
}


#' @title Visualize the results of association analysis for panel data
#' @description Visualize the results of association analysis for panel data
#' @usage VizPanelAsso = function(PID, OutPath, VarsY, VarsN, Layout = "volcano",
#'     Brightness = "dark", Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoPanel
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsN chr. Choose the single factor or multiple factor model. 
#'     Available options include "single.factor" and "multiple.factor"
#' @param Layout chr. Visualization layout. Available options include "forest" and "volcano".
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".  
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., cell, nature, science, lancet, nejm, and jama). 
#' @details 
#' @return A list containing the plots of association analysis results.
#' @export
#' @examples res <- InitPanel()
#'    res1 = LoadPanel(PID = res$PID, UseExample = "example#1")
#'    res2 = TransImput(PID=res$PID,Group="T",Vars="all.x",Method="lod")
#'    res3 = DelNearZeroVar(PID = res$PID)
#'    res4 = DelMiss(PID = res$PID)
#'    res5 = TransType(PID=res$PID,Vars="Y1",To="factor")
#'    res6 = TransScale(PID=res$PID,Group="T",Vars="all.x",Method="normal")
#'    res7 = TransDummy(PID=res$PID,Vars="default")
#'    res8 = PanelAsso(PID=res$PID, OutPath = OutPath, VarsY = "Y1", 
#'    VarsX = "X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12", VarsN = "single.factor",
#'     VarsRandomIpt = "SubjectID", VarsRandomSlp = "none", IncCova = "F")
#'    res9 = VizPanelAsso(PID = res$PID, OutPath = OutPath, VarsY = "Y1", 
#'     VarsN = "single.factor", Layout = "forest", Brightness = "dark",Palette = "default1")
#'    res10 = PanelAsso(PID=res$PID, OutPath = OutPath, VarsY = "Y1", 
#'     VarsX = "X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12", VarsN = "multiple.factor",
#'     VarsRandomIpt = "SubjectID", VarsRandomSlp = "none", IncCova = "F")
#'    res11 = VizPanelAsso(PID = res$PID, OutPath = OutPath, VarsY = "Y1", 
#'     VarsN = "single.factor", Layout = "forest", Brightness = "dark",Palette = "default1")
#' @author Bin Wang 

VizPanelAsso = function(PID,
                        OutPath = "default",
                        VarsY,
                        VarsN,
                        EffectThr = 0.5,
                        Layout = "volcano",
                        Brightness = "dark",
                        Palette = "default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  message("It may take some time. Thanks for your patient waiting!")
  
  url = paste0(urlhead,'VizPanelAsso')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VarsY = VarsY,
                               VarsN = VarsN,
                               EffectThr = EffectThr,
                               Layout = Layout,
                               Brightness = Brightness,
                               Palette = Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))

  for (name in names(results$AssoPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/PanelAsso/',name,".png"),
                      plot = results$AssoPlot[[name]],
                      width = results$AssoPlot_para[[name]][['width']],
                      height = results$AssoPlot_para[[name]][['height']],
                      units = "cm",dpi = 300,
                      limitsize = FALSE),
      silent = TRUE
    )
  }
  return(results$AssoPlot)
}


#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by any initial functions.
#' @details 
#' @return Exit status
#' @export
#' @examples res = InitBioLink()
#'    res = LoadBioLink(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}




