urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoSurvival module
#' @description Initialize ExpoSurvival module analysis. It can generate an R6
#'     class object integrating all the analysis information.
#' @usage InitSurv()
#' @details InitSurv uses R6 package to generate an R6 class object where
#'    parameters to be used for the following mediation module program are
#'    initialized and save in that object. All executed function codes in the
#'    ExpoSurvival packaged will be recorded in the form of log text in that
#'    object. Furthermore, a program ID (i.e., PID) is randomly created for the
#'    users to identify their own program.
#' @return An R6 class object.
#' @export
#' @examples res <- InitSurv()
#' @author Changxin Lan, Bin Wang(corresponding author)
InitSurv = function(){
  url = paste0(urlhead,'InitSurv')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}

#' @title Load data file for Survival module
#' @description Load data file for Survival module
#' @usage LoadSurv(PID = PID, UseExample = "default", ...)
#' @param PID chr. Program ID. It must be the same with the PID generated by
#'    InitSurv.
#' @param UseExample chr. Method of uploading data. If "default"，
#'    user should upload their own data files, or use "example#1"
#'    provided by this module.
#' @param DataPath chr. Input data file directory, e.g.
#'    "D:/test/eg_Surv_data.xlsx". It should be noted that the slash
#'    symbol is "/", not "\".
#' @param VocaPath chr. Input vocabulary file directory, e.g.
#'    "D:/test/eg_Surv_voca.xlsx". It should be noted that the slash
#'    symbol is "/", not "\".
#' @details LoadSurv function loads the data file and the vocabulary file into
#'    the R6 object that InitSurv created. Noted that there are several data
#'    format requirments for the data and vocabulary file.
#'    For data file,the first three columns should be named as "SampleID", "SubjectID", and "Group", respectively.
#'    For the "Group" variable, only two values can be used, i.e. "train" and "test". If there is no data for test, all values should be set as "train".
#'    For outcome variables, their initials must be set as "Y" and serialized by adding Arabic numerals if needed, e.g., Y1, Y2, Y3. In this module, the survival time (Y1) and status (Y2) must be provided.For exposure variables, their initials must be set as "X" and serialized by adding Arabic numerals if needed, e.g., X1, X2, X3.
#'    For covariate variables, their initials must be set as "C" and serialized by adding Arabic numerals if needed, e.g., C1, C2, C3. It should be noted the covariates are not required if users don’t have.
#'    For vocabulary file, the first two columns must be named as "SerialNo" and "FullName", respectively.
#'    The list of SerialNo of outcomes, exposure, and covariates should be the same with the column names of "Data file".
#'    The list of the FullName is prepared as users’ like.

#' @return An R6 class object containing the input data and vocabulary file.
#' @export
#' @examples res <- InitSurv()
#'    res1 <- LoadSurv(PID = res$PID, UseExample = "example#1", DataPath = NULL,
#'    VocaPath = NULL)
#' @author Changxin Lan, Bin Wang(corresponding author)
LoadSurv =function(PID,
                   UseExample="default",
                   DataPath=NULL,
                   VocaPath=NULL){
  url = paste0(urlhead,'LoadSurv')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)
    vodata = readxl::read_excel(VocaPath)
  }else{
    exdata = NULL
    vodata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID=PID,
                                         UseExample=UseExample,
                                         Expodata=exdata,
                                         Vocadata=vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}

#' @title Find covariates
#' @description Find covariates
#' @usage FindCovaSurv = function(PID, OutPath = "default", TimeY, EventY, VarsC_Prior = "default", 
#'     VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoCros
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param TimeY chr. Outcome variable of survival time used for modelling. Only one variable can be entered.
#' @param EventY chr. Outcome variable of status used for modelling. Only one variable can be entered.
#' @param VarsC_Prior chr. Potential covariates needing further statistical test. 
#'     The default value is all covariate variables listed in the data file. 
#' @param VarsC_Fixed chr. Covariate variables fixed in the model by users.
#' @param Method chr. Methods for screening the covariates, including two options, 
#'     i.e. "single.factor" and "two.stage".
#' @param Thr num. Threshold of the P-value for screening the covariates. It is 
#'     ranging 0.05-0.25. The default value is 0.1. 
#' @details 
#' @return A list containing the selected covariates.
#' @export
#' @examples res <- InitSurv()
#'    res1 = LoadSurv(PID = res$PID, UseExample = "example#1")
#'    res2 = TransDummy(PID=res$PID, Vars="default")
#'    res3 = FindCovaSurv(PID=res$PID, TimeY = "Y1", EventY= 'Y2',
#'    VarsC_Prior = "default", VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#'    FuncExit(PID = res$PID)
#' @author Changxin Lan, Bin Wang(corresponding author)
FindCovaSurv = function(PID,
                        OutPath="default",
                        TimeY,
                        EventY,
                        VarsC_Prior="default",
                        VarsC_Fixed= NULL,
                        Method="single.factor",
                        Thr=0.1){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  
  if(length(VarsC_Fixed) == 0){
    VarsC_Fixed = ""
  }
  url = paste0(urlhead,'FindCovaSurv')
  res = httr::POST(url,
                   body = list(PID=PID,
                               FindCovaSurvTimeY=TimeY,
                               FindCovaSurvEventY=EventY,
                               FindCovaSurvVarsC_Prior=VarsC_Prior,
                               FindCovaSurvVarsC_Fixed=VarsC_Fixed,
                               FindCovaSurvMethod=Method,
                               FindCovaSurvThr=Thr),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/Covariates")
  if(!file.exists(path)){dir.create(path)}
  vroom::vroom_write(results$FindCovaSurv,paste0(path, "/Covariates.csv"),",")

  return(results)
}


#' @title Association analysis
#' @description Association analysis for survival data
#' @usage SurvAsso = function(PID, OutPath = "default",
#'     TimeY, EventY,VarsX='all.x',VarsN = "single.factor",VarsSel = F,
#'     IncCova = T)
#' @param PID chr. Program ID. It must be the same with the PID generated by InitSurv()
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param TimeY chr. Outcome variable of survival time used for modelling. Only one variable can be entered.
#' @param EventY chr. Outcome variable of status used for modelling. Only one variable can be entered.
#' @param VarsX Exposure variable used for modeling. The default option is 
#'     "all.x" (All exposure variables are included). Users can also choose available variables. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param VarsN chr. Choose the single factor or multiple factor model. 
#'     Available options include "single.factor" and "multiple.factor"
#' @param VarsSel lgl. T (or TRUE) and F (or FALSE). Whether to select the significant variable for the final model. 
#'     Available options includes T and F
#' @param IncCova lgl. T (or TRUE) and F (or FALSE). Whether to include the covariate
#'     selected in the function "FindCovaSurv"
#'
#' @return A list containing the association analysis results.
#' @export
#'
#' @examples res <- InitSurv()
#'    res1 = LoadSurv(PID = res$PID, UseExample = "example#1")
#'    res2 = TransDummy(PID=res$PID, Vars="default")
#'    res3 = FindCovaSurv(PID=res$PID, TimeY = "Y1", EventY= 'Y2',
#'    VarsC_Prior = "default", VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#'    res4 = SurvAsso(PID=res$PID, TimeY = "Y1", EventY= 'Y2',VarsX='all.x',
#'    VarsN="single.factor",VarsSel=T,IncCova=T)
#'    FuncExit(PID = res$PID)
#' @author Changxin Lan, Bin Wang(corresponding author)
SurvAsso = function(PID,
                    OutPath='default',
                    TimeY,
                    EventY,
                    VarsX='all.x',
                    VarsN="single.factor",
                    VarsSel=T,
                    IncCova=T){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  message("It may take some time. Thanks for your patient waiting!")
  url = paste0(urlhead,'SurvAsso')
  res = httr::POST(url,
                   body = list(PID=PID,
                               SurvAssoTimeY=TimeY,
                               SurvAssoEventY=EventY,
                               SurvAssoVarsX=VarsX,
                               SurvAssoVarsN=VarsN,
                               SurvAssoVarsSel=VarsSel,
                               SurvAssoIncCova=IncCova),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/Association")
  if(!file.exists(path)){dir.create(path)}
  vroom::vroom_write(results$coxph_res,paste0(path, "/", EventY,"_",VarsN,".csv"),",")
  return(results)
}

#' @title Visualize association analysis
#' @description Visualize association analysis
#' @usage VizSurvAsso = function(PID, OutPath = "default",VarsN = "single.factor",
#'     Layout = "volcano",Brightness = "light",Palette = "default1",ColorFor= "p.value",SizeFor= "p.value")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitSurv()
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsN chr. Choose the single factor or multiple factor model. 
#'     Available options include "single.factor" and "multiple.factor"
#' @param Layout chr. Visualization layout. Available options include "forest" and "volcano".
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark". 
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., "cell", "nature", "science", "lancet", "nejm", and "jama"). 
#' @param ColorFor chr. Volcano plot dot color. Available options include "p.value" and "hr".
#' @param SizeFor chr. Volcano plot dot size. Available options include "p.value" and "hr".
#'
#' @return A list containing the results' plot.
#' @export
#'
#' @examples res <- InitSurv()
#'    res1 = LoadSurv(PID = res$PID, UseExample = "example#1")
#'    res2 = TransDummy(PID=res$PID, Vars="default")
#'    res3 = FindCovaSurv(PID=res$PID, TimeY = "Y1", EventY= 'Y2',
#'    VarsC_Prior = "default", VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#'    res4 = SurvAsso(PID=res$PID, TimeY = "Y1", EventY= 'Y2',VarsX='all.x',
#'    VarsN="single.factor",VarsSel=T,IncCova=T)
#'    res5 = VizSurvAsso(PID=res$PID,VarsN="single.factor",Layout="volcano",Brightness= "light",
#'    Palette = "default1",ColorFor= "p.value",SizeFor= "p.value")
#'    FuncExit(PID = res$PID)
#' @author Changxin Lan, Ning Gao, Bin Wang(corresponding author)
VizSurvAsso = function(PID,
                       OutPath='default',
                       VarsN="single.factor",
                       Layout="volcano",
                       Brightness= "light",
                       Palette = "default1",
                       ColorFor= "p.value",
                       SizeFor= "p.value"){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  message("It may take some time. Thanks for your patient waiting!")
  url = paste0(urlhead,'VizSurvAsso')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizSurvAssoVarsN=VarsN,
                               VizSurvAssoLayout =Layout,
                               VizSurvAssoBrightness = Brightness,
                               VizSurvAssoPalette = Palette,
                               VizSurvAssoColorFor = ColorFor,
                               VizSurvAssoSizeFor =SizeFor),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/Association")
  if (VarsN=="single.factor"){
    for (i in c(1:length(results$SurvCurvePlot))){
      ggplot2::ggsave(paste0(path, "/", names(results$SurvCurvePlot)[i], "_SingleFactor_SurvCurve.png"),
                      plot = results$SurvCurvePlot[[i]],
                      width = 35,
                      height = 20,
                      units = "cm")
    }
  }else{
    ggplot2::ggsave(paste0(path, "/MultipleFactor_SurvCurve.png"),
           plot = results$SurvCurvePlot,
           width = 35,
           height = 20,
           units = "cm")
  }
  if(Layout =="forest"){
    ggplot2::ggsave(paste0(path, "/",VarsN,"_forest_",Brightness,"_",Palette,".png"),
                    plot = results$ForestPlot,
                    width = 15,
                    height = 5+10*ceiling(results$nrow_forest/50),
                    units = "cm",dpi = 300,
                    limitsize = FALSE)
  }
  if (Layout =="volcano"){
    ggplot2::ggsave(paste0(path, "/",VarsN,"_volcano_",Brightness,"_",Palette,"_colorforhr_sizeforpvalue.png"),
                    plot = results$VolcanoPlot,
                    width = 20+5*ceiling(results$nrow_vocanol/50),
                    height = 9+5*ceiling(results$nrow_vocanol/50),
                    units = "cm",dpi = 300)
  }
  return(results)
}


#' @title Build prediction models
#' @description Build prediction models
#' @usage SurvPred = function(PID,OutPath = "default",TimeY,EventY,VarsX = "all.x",
#'     IncCova = T,RsmpMethod = "cv",Folds = 3,Ratio = 0.667,Repeats = 3)
#' @param PID chr. Program ID. It must be the same with the PID generated by InitSurv()
#' @param OutPath  chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param TimeY chr. Outcome variable of survival time used for modelling. Only one variable can be entered.
#' @param EventY chr. Outcome variable of status used for modelling. Only one variable can be entered.
#' @param VarsX chr. Exposure variable used for modeling. The default option is 
#'     "all.x" (All exposure variables are included). Users can also choose available variables. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param IncCova lgl. Whether to include the covariate selected in the function of "FindCovaSurv".
#'     Available options include T (or TRUE) and F (or FALSE).
#' @param RsmpMethod chr. Three resampling methods options for internal validation, including 
#'     "cv" (i.e.,Cross validation) , "bootstrap", and "holdout".
#' @param Folds num. Folds of Cross-validation resampling. It is ranging 2-10.
#' @param Ratio num. Ratio of Bootstrap resampling. It is ranging 0.4-0.9.
#' @param Repeats num. Number of Bootstrap resampling. It is ranging 2-20.
#'
#' @return  A list containing the prediction performance evaluation.
#' @export
#'
#' @examples res <- InitSurv()
#'    res1 = LoadSurv(PID = res$PID, UseExample = "example#1")
#'    res2 = TransDummy(PID=res$PID, Vars="default")
#'    res3 = FindCovaSurv(PID=res$PID, TimeY = "Y1", EventY= 'Y2',
#'    VarsC_Prior = "default", VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#'    res4 = SurvPred(PID=res$PID, TimeY = "Y1", EventY= 'Y2',VarsX='all.x',
#'    IncCova=T,RsmpMethod="cv",Folds=3,Ratio=0.667,Repeats=3)
#'    FuncExit(PID = res$PID)
#' @author Changxin Lan, Bin Wang(corresponding author)
SurvPred = function(PID,
                    OutPath='default',
                    TimeY,
                    EventY,
                    VarsX= "all.x",
                    IncCova=T,
                    RsmpMethod="cv",
                    Folds=3,
                    Ratio=0.667,
                    Repeats=3){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  message("It may take some time. Thanks for your patient waiting!")
  url = paste0(urlhead,'SurvPred')
  res = httr::POST(url,
                   body = list(PID=PID,
                               SurvPredTimeY=TimeY,
                               SurvPredEventY=EventY,
                               SurvPredVarsX=VarsX,
                               SurvPredIncCova=IncCova,
                               SurvPredRsmpMethod=RsmpMethod,
                               SurvPredFolds=Folds,
                               SurvPredRatio=Ratio,
                               SurvPredRepeats=Repeats),
                   encode = 'json',
                   httr::timeout(600))
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/Prediction")
  if(!file.exists(path)){dir.create(path)}
  vroom::vroom_write(results$bmrout,paste0(path, "/",EventY, "_BMR_", RsmpMethod,".csv"),",")
  for (i in c(1:length(results$predout))){
    try(vroom::vroom_write(data.frame(results$predout[[i]]),paste0(path, "/",EventY, "_Prediton_", 
                                                                   names(results$predout)[i],".csv"),","),silent = TRUE)
  }
  return(results)
}

#' @title Visualize the prediction performance
#' @description Visualize the prediction performance
#' @usage VizSurvPred = function(PID,OutPath = "default",Layout = "curve",
#'     Brightness = "light",Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitSurv()
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set. 
#' @param Layout chr. Visualization layout. Available options include "curve" , "bar" and 'all'.
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark". 
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., "cell", "nature", "science", "lancet", "nejm", and "jama"). 
#'
#' @return A list containing the results' plot.
#' @export
#'
#' @examples res <- InitSurv()
#'    res1 = LoadSurv(PID = res$PID, UseExample = "example#1")
#'    res2 = TransDummy(PID=res$PID, Vars="default")
#'    res3 = FindCovaSurv(PID=res$PID, TimeY = "Y1", EventY= 'Y2',
#'    VarsC_Prior = "default", VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#'    res4 = SurvPred(PID=res$PID, TimeY = "Y1", EventY= 'Y2',VarsX='all.x',
#'    IncCova=T,RsmpMethod="cv",Folds=3,Ratio=0.667,Repeats=3)
#'    res5 = VizSurvPred(PID=res$PID,Layout="curve",Brightness="light",Palette='default1')
#'    FuncExit(PID = res$PID)
#' @author Changxin Lan, Ning Gao, Bin Wang(corresponding author)
VizSurvPred = function(PID,
                       OutPath='default',
                       Layout="curve",
                       Brightness="light",
                       Palette='default1'){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  message("It may take some time. Thanks for your patient waiting!")
  url = paste0(urlhead,'VizSurvPred')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizeSurvPredLayout =Layout,
                               VizeSurvPredBrightness =Brightness,
                               VizeSurvPredPalette = Palette
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/Prediction")
  if(!file.exists(path)){dir.create(path)}
  try(
    ggplot2::ggsave(paste0(path, "/learner_fit_survcurve_comp_",Brightness,"_",Palette,".png"),
                    plot = results$PredSurvCurvPlot,
                    width = 30,
                    height = 20,
                    units = "cm"),
    silent = TRUE
  )
  try(
    ggplot2::ggsave(paste0(path, "/BMR_barplot_",Brightness,"_",Palette,".png"),
                    plot =results$BmrBarPlot,
                    width = 25,
                    height = 15,
                    units = "cm",dpi = 300),
    silent = TRUE
  )
  try(
    ggplot2::ggsave(paste0(path, "/BMR_Pointplot_",Brightness,"_",Palette,".png"),
                    plot = results$BmrPointPlot,
                    width = 25,
                    height = 15,
                    units = "cm",dpi = 300)
  )
  return(results)
}


#' @title Compare the survival curves of two groups
#' @description Compare the survival curves of two groups
#' @usage VizSurvCompGroup = function(PID,OutPath = "default",TimeY,EventY,
#'     VarsG,Model='km',VarsAdj,AdjMethod='average',Brightness = "light",Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitSurv()
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set. 
#' @param TimeY chr. Outcome variable of survival time used for modelling. Only one variable can be entered.
#' @param EventY chr. Outcome variable of status used for modelling. Only one variable can be entered. 
#' @param VarsG chr.  Grouping variable, must be a binary variable.
#' @param Model chr. Methods to depict the survival curve. Options include 'km' (Kaplan-Meier estimate) and 
#'     "coxph" (Cox proportional hazards regression mode).
#' @param VarsAdj If you choose the cox model, co-variables used for modelling. 
#'     It should be noted that there is fixed format for the entering characters separated with comma and without space, e.g., X1,X2,X3.
#' @param AdjMethod If you choose the cox model, method for adjusting model, include: "average","single","margin" and "conditional".
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".  
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., "cell", "nature", "science", "lancet", "nejm", and "jama"). 
#'
#' @return A list containing the results' plot.
#' @export 
#'
#' @examples res <- InitSurv()
#'    res1 = LoadSurv(PID = res$PID, UseExample = "example#1")
#'    res6 = VizSurvCompGroup(PID=res$PID,TimeY="Y1",EventY="Y2",VarsG="C3",
#'    Model="km",,Brightness="light",Palette='default1')
#'    FuncExit(PID = res$PID)
#' @author Changxin Lan, Ning Gao, Bin Wang(corresponding author)
VizSurvCompGroup = function(PID,
                            OutPath='default',
                            TimeY,
                            EventY,
                            VarsG,
                            Model='km',
                            VarsAdj,
                            AdjMethod='average',
                            Brightness='light',
                            Palette='default1'){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  message("It may take some time. Thanks for your patient waiting!")
  url = paste0(urlhead,'VizSurvCompGroup')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizSurvCompGroupTimeY=TimeY,
                               VizSurvCompGroupEventY=EventY,
                               VizSurvCompGroupVarsG=VarsG,
                               VizSurvCompGroupVarsAdj=VarsAdj,
                               VizSurvCompGroupModel=Model,
                               VizSurvCompGroupAdjMethod=AdjMethod,
                               VizSurvCompGroupBrightness =Brightness,
                               VizSurvCompGroupPalette =Palette),
                   encode = 'json')

  results = unserialize(httr::content(res))
  path = paste0(OutPath, "/VizSurvCompGroup")
  if(!file.exists(path)){dir.create(path)}
  if (!is.null(results$Comp_KM_Plot)){
    for (i in c(1:length(results$Comp_KM_Plot))){
      ggplot2::ggsave(paste0(path, "/km", "_",EventY,"_",
                             names(results$Comp_KM_Plot)[i],"_",
                             Brightness,"_",Palette,".png"),
                      plot = results$Comp_KM_Plot[[i]],
                      width = 35,
                      height = 60,
                      units = "cm"
      )
    }
  }

 if (!is.null(results$Comp_Coxph_Plot)){
   for (i in c(1:length(results$Comp_Coxph_Plot))){
     ggplot2::ggsave(paste0(path, "/coxph_", EventY, "_",
                            names(results$Comp_Coxph_Plot)[i],"_",
                            AdjMethod,"_", Brightness,"_",Palette,".png"),
                     plot = results$Comp_Coxph_Plot[[i]],
                     width = 35,
                     height = 20,
                     units = "cm",dpi = 300)
   }
 }
  return(results)
}



#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It should be the same with the PID generated by initial functions.
#' @details 
#' @return Exit status
#' @export
#' @examples res = InitTidy()
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}



