
library(gridExtra)
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoStatLink module
#' @description Initialize ExpoStatLink module analysis. It can generate an R6 class object.
#' @usage InitStatLink()
#' @param 
#' @details ExpoStatLink module is designed to find the statistical relationships 
#'     between exposure factors and health outcome. 
#' @return An R6 class object.
#' @export
#' @examples res <- InitStatLink()
#' @author Bin Wang 

InitStatLink = function(){
  url = paste0(urlhead,'InitStatLink')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Load data file for ExpoStatLink for module
#' @description Load data file for ExpoStatLink module
#' @usage LoadStatLink(PID, UseExample = "default", DataPath=NULL, VocaPath=NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoStatLink
#' @param UseExample chr. Method of uploading data. If "default"，user should upload their own data files, 
#'    or use "example#1" provided by this module. 
#' @param DataPath chr. Input directory of data file, e.g. "D:/test/eg_data_biolink.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @param VocaPath chr. Input directory of vocabulary file, e.g. "D:/test/eg_voca_biolink.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @details 
#' @return An R6 class object containing the input data.
#' @export
#' @examples res <- InitStatLink()
#'    res = LoadStatLink(PID = res$PID, UseExample = "example#1")
#' @author Bin Wang 

LoadStatLink =function(PID,
                       UseExample="default",
                       DataPath=NULL,
                       VocaPath=NULL){
  url = paste0(urlhead,'LoadStatLink')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)

    vodata = readxl::read_excel(VocaPath)
  }else{
    exdata = NULL
    vodata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID=PID,
                                         UseExample=UseExample,
                                         Expodata=exdata,
                                         Vocadata=vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}



#' @title Build statistical link for cross-sectional data.
#' @description Build statistical link for cross-sectional data.
#' @usage StatLinkCros(PID, OutPath = "default", VarsY, VarsX, LinkModel = "ranger",
#'     ObsrPartType = "raw",ObsrPartNum = "50",ObsrProfType = "partial",
#'     ObsrProfNum = "100",ObsrProfVars = "all.x",ObsrProfGeom = "profiles",
#'     SubjPredSeq = "none",SubjPartType = "break_down")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoStatLink
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modelling. Only one variable can be entered.
#' @param VarsX chr. Exposure variable used for modelling. The default option is 
#'     "all.x" (All exposure variables are included). Users can also choose available variables. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param LinkModel chr. Methods to interpret the model. Options include "ranger" (random forest), 
#'     "glmnet" (elastic net), "svm" (support vector machine), "glm" (linear regression), 
#'     "gam" (generalized additive model), and "xgboost" (eXtreme gradient boosting).
#' @param ObsrPartType chr. Type of transformation that should be applied for dropout loss. 
#'     Options include "raw" (drop losses), "ratio" (drop_loss/drop_loss_full_model), 
#'     and "difference" (drop_loss - drop_loss_full_model)
#' @param ObsrPartNum chr. Number of observations that should be sampled for calculation 
#'     of variable importance. The default means variable importance will be calculated 
#'     on whole dataset (no sampling). If "defult", use all Obsrrvations. 
#' @param ObsrProfType chr. Type of variable profile. Options include "partial", 
#'     "conditional", and "accumulated"
#' @param ObsrProfNum int. Number of observations used for calculation of aggregated profiles. 
#'     By default 100.
#' @param ObsrProfVars chr. Names of variables to be explained. If "all.x", all "X variable" above are chosen.
#' @param ObsrProfGeom chr. Layout of the explanation profile in dataset level 
#'     including "aggregates", "profiles" or "points".
#' @param SubjPredSeq chr. Subjects which need explanation. Options include "all" (all the subjects),
#'     "none" (no subjects), and "other" (copy the subject list by clicking "Available vars").
#' @param SubjPartType chr. Layout of the explanation profile in subject level. 
#'     Options include "shap", "oscillations", "break_down", and "none".
#' @details 
#' @return A list containing all the statistical explanation results.
#' @export
#' @examples res <- InitStatLink()
#'    res1 = LoadStatLink(PID = res$PID, UseExample = "example#1")
#'    res2 = StatLinkCros(PID=res$PID, OutPath = OutPath, VarsY = "Y1" ,VarsX = "all.x",
#'    LinkModel = "ranger",ObsrPartType = "raw" ,ObsrPartNum  = "50",
#'    ObsrProfType = "partial" ,ObsrProfNum = "100", ObsrProfVars = "all.x",
#'    ObsrProfGeom = "profiles",SubjPredSeq = "S1,S2,S3",SubjPartType = "break_down")
#' @author Bin Wang 

StatLinkCros = function(PID,
                        OutPath = "default",
                        VarsY,
                        VarsX,
                        LinkModel = "ranger",
                        ObsrPartType = "raw",
                        ObsrPartNum = "50",
                        ObsrProfType = "partial",
                        ObsrProfNum = "100",
                        ObsrProfVars = "all.x",
                        ObsrProfGeom = "profiles",
                        SubjPredSeq = "none",
                        SubjPartType = "break_down"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  message("It may take some time. Thanks for your patient waiting!")
  
  url = paste0(urlhead,'StatLinkCros')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VarsY = VarsY,
                               VarsX = VarsX,
                               LinkModel = LinkModel,
                               ObsrPartType = ObsrPartType,
                               ObsrPartNum = ObsrPartNum,
                               ObsrProfType = ObsrProfType,
                               ObsrProfNum = ObsrProfNum,
                               ObsrProfVars = ObsrProfVars,
                               ObsrProfGeom = ObsrProfGeom,
                               SubjPredSeq = SubjPredSeq,
                               SubjPartType = SubjPartType),
                   encode = 'json')
  results = unserialize(httr::content(res))
  
  dir.create(paste0(OutPath,'/Dataset_Level'))
  for (name in names(results$CrosVipTable)){
    try(
      vroom::vroom_write(results$CrosVipTable[[name]],
                         paste0(OutPath,'/Dataset_Level/', name,".csv"),
                         delim = ","),silent = TRUE
    )
  }
  
  for (name in names(results$CrosVipPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/Dataset_Level/',name,".png"),
                      plot = results$CrosVipPlot[[name]],
                      width = 35,
                      height = 20,
                      units = "cm",dpi = 300),silent = TRUE
    )
  }
  
  for (name in names(results$CrosProfPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/Dataset_Level/',name,".png"),
                      plot = results$CrosProfPlot[[name]],
                      width =  35,
                      height = 20,
                      units = "cm",dpi = 300),silent = TRUE
    )
  }
    
  for (name in names(results$CrosProfPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/Dataset_Level/',name,".png"),
                      plot = results$CrosProfPlot[[name]],
                      width =  35,
                      height = 20,
                      units = "cm",dpi = 300),silent = TRUE
    )
  }
  
  dir.create(paste0(OutPath,'/Subject_Level'))
  for (name in names(results$CrosSubjPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/Subject_Level/',name,".png"),
                      plot = results$CrosSubjPlot[[name]],
                      width =  35,
                      height = 20,
                      units = "cm",dpi = 300),silent = TRUE
    )
  }
    
  return(results)
}



#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by any initial functions.
#' @details 
#' @return Exit status
#' @export
#' @examples res = InitBioLink()
#'    res = LoadBioLink(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}





