
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoBioLink module
#' @description Initialize ExpoBioLink module analysis. It can generate an R6 class object
#'     integrating all the analysis information.
#' @usage InitBioLink()
#' @param
#' @details ExpoBioLink module is designed to find the biological relationships between
#'     exposure factors and health outcome. This module adopts the most frequently-used and
#'     authoritative databases, e.g., T3DB, CTD, ToxCast, StringDB, STITCH, KEGG, and GO.
#' @return An R6 class object.
#' @export
#' @examples res <- InitBioLink()
#' @author Mingliang Fang, Bin Wang,(corresponding author)


InitBioLink = function(){
  url = paste0(urlhead,'InitBioLink')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Load data file for BioLink module
#' @description Load data file for BioLink module.
#' @usage LoadBioLink(PID, UseExample = "default", DataPath=NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param UseExample chr. Method of uploading data. If "default"，user should upload their own data files,
#'    or use "example#1" provided by this module.
#' @param DataPath chr. Input file directory, e.g. "D:/test/eg_biolink.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @details
#' @return An R6 class object containing the input data.
#' @export
#' @examples res <- InitBioLink()
#'    res = LoadBioLink(PID = res$PID, UseExample = "example#1")
#' @author Mingliang Fang, Bin Wang (corresponding author)

LoadBioLink =function(PID,
                      UseExample = "default",
                      DataPath = NULL){
  url = paste0(urlhead,'LoadBioLink')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)
  }else{
    exdata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID=PID,
                                         UseExample=UseExample,
                                         Expodata=exdata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Convert different IDs to the unified ExposomeX IDs
#' @description Convert the IDs of exposure, chemicals, metabolites, or proteins to the unified ExposomeX ID,
#'     i.e., unified identifier in ExposomeX platform
#' @usage ConvToExpoID(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @details
#' @return A data frame containing the converted ID information.
#' @export
#' @examples res = InitBioLink()
#'    res1 = LoadBioLink(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#' @author Mingliang Fang, Weinan Lin, Bin Wang (corresponding author)

ConvToExpoID = function(PID,
                        OutPath="default"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'ConvToExpoID')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  results = unserialize(httr::content(res))

  dir.create(paste0(OutPath,'/ConvToExpoID'))

  try(vroom::vroom_write(results$Data,paste0(OutPath,"/ConvToExpoID/ExpoData.csv"),
                         delim = ","),silent = TRUE
  )
  return(results$Data)
}


#' @title Build the biological link
#' @description Build the biological link between the exposures and diseases
#' @usage BioLink(PID, Mode="GO",ChemCas="default", ChemInchikey="default",
#'    DiseaseID="default", MetabolomeID="default", MetBiospec="blood", ProteomeID="default")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory. e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'    If "default", the current working directory will be set.
#' @param Mode chr. Method to build the biological link between exposures and diseases.
#'    Available options include "PPI" (i.e., protein-protein interaction) and "GO" (i.e., gene ontoloty).
#' @param ChemCas chr. CAS Registry Number of chemicals. Default means using the values in the input data file.
#'    Users can also copy the part of them by clicking "Available vars". It should be noted that
#'    there is fixed format for the entering characters separated with comma and without space,
#'    e.g., "7440-43-9,333-41-5,20461-54-5".
#' @param ChemInchikey chr. InChiKey serial number of chemicals. Default means using the values in the input data file.
#'    It should be noted that there is fixed format for the entering characters separated with comma and without space,
#'    e.g., "WABPQHHGFIMREM-UHFFFAOYSA-N,BTAGRXWGMYTPBY-UHFFFAOYSA-N,IAKOZHOLGAGEJT-UHFFFAOYSA-N".
#' @param DiseaseID chr. ID of the concerned diseases. Both IDs from OMIM (e.g., OMIM:220100) and
#'    MESH (e.g., MESH:C536409) are accepted. It should be noted that there is fixed format
#'    for the entering characters separated with comma and without space,
#'    e.g., "OMIM:244200,MESH:C536409,OMIM:181500".
#' @param MetabolomeID chr. KEGG entry number of metabolites. Default means using the values
#'    in the input data file. Users can also copy the part of them by clicking "Available vars".
#'    It should be noted that there is fixed format for the entering characters separated with comma
#'    and without space, e.g., "C00022,C00117,C00794".
#' @param MetBiospec chr. Biological sample matrix for the metabolome analysis.
#'    Options include "Blood" and "Urine".
#' @param ProteomeID chr. Protein ID. Both IDs of Ensembl and UniProt are accepted.
#'    Default means using the values in the input data file. Users can also copy the part of them
#'    by clicking "Available vars". It should be noted that there is fixed format for the entering characters
#'    separated with comma and without space, e.g., "Q9Y3X0,Q8N5I3,ENSP00000000233,ENSP00000000412".
#' @details
#' @return A list object containing the edges and nodes of the biological link.
#' @export
#' @examples res = InitBioLink()
#'    res1 = LoadBioLink(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#'    res3 = BioLink(PID = res$PID, OutPath="default", Mode = "GO", ChemCas = "default",
#'    ChemInchikey = "default",DiseaseID = "default",MetabolomeID = "default",
#'    MetBiospec = "blood", ProteomeID = "default")
#' @author Mingliang Fang, Bin Wang (corresponding author)

BioLink = function(PID,
                   OutPath="default",
                   Mode,
                   ChemCas = "default",
                   ChemInchikey = "default",
                   DiseaseID = "default",
                   MetabolomeID = "default",
                   MetBiospec = "blood",
                   ProteomeID = "default"
                   ){
  if(OutPath == "default"){
    OutPath = getwd()
  }

  message("It may take some time. Thanks for your patient waiting!")

  url = paste0(urlhead,'BioLink')
  res = httr::POST(url,
                   body = list(PID=PID,
                               BiolinkMode=Mode,
                               BiolinkChemCas=ChemCas,
                               BiolinkChemInchikey=ChemInchikey,
                               BiolinkDiseaseID=DiseaseID,
                               BiolinkMetabolomeID=MetabolomeID,
                               BiolinkMetBiospec=MetBiospec,
                               BiolinkProteomeID=ProteomeID
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/BioLink'))
  try(vroom::vroom_write(results$Edges,paste0(OutPath,"/BioLink/",Mode,"_edges.csv"),
                         delim = ","),silent = TRUE
  )
  try(vroom::vroom_write(results$Nodes,paste0(OutPath,"/BioLink/",Mode,"_Nodes.csv"),
                         delim = ","),silent = TRUE
  )
  return(results)
}


#' @title Visualize the biological link
#' @description Visualize the biological link. It should be noted that the corresponding link
#'     has been built by BioLink function prior to using it.
#' @usage BioLink = function(PID,OutPath="default",Mode,ChemCas = "default",ChemInchikey = "default",DiseaseID = "default",
#'     MetabolomeID = "default",MetBiospec = "blood",ProteomeID = "default")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory. e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param Mode chr. Method to build the biological link between exposures and diseases.
#'    Available options include "PPI" (i.e., protein-protein interaction) and "GO" (i.e., gene ontoloty).
#' @param Layout chr. Visualization layout. Available options include "force-directed" and "degree-circle".
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., cell, nature, science, lancet, nejm, and jama).
#' @details
#' @return A list object containing the plot of the biological link. This plot can be further processed using ggplot2 package.
#' @export
#' @examples res = InitBioLink()
#'    res1 = LoadBioLink(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#'    res3 = BioLink(PID = res$PID, OutPath="default", Mode = "GO", ChemCas = "default",
#'    ChemInchikey = "default",DiseaseID = "default",MetabolomeID = "default",
#'    MetBiospec = "blood", ProteomeID = "default")
#'    res4 = VizBioLink(PID = res$PID, Mode = 'GO', Layout = "force-directed",
#'    Brightness = "dark", Palette = "default1")
#' @author Mingliang Fang, Ning Gao, Bin Wang (corresponding author)

VizBioLink = function(PID,
                      OutPath="default",
                      Mode,
                      Layout = "force-directed",
                      Brightness = "dark",
                      Palette = "default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizBioLink')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizBioLinkMode=Mode,
                               VizBioLinkLayout =Layout,
                               VizBioLinkBrightness = Brightness,
                               VizBioLinkPalette = Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))

  ggplot2::ggsave(paste0(OutPath,'/BioLink/', Mode,"_",Layout,"_",
                         Brightness,"_",Palette,'.png'),
         plot = results$Plot[[1]],
         width =  20,
         height = 20,
         units = "cm")
  return(results$Plot)
}


#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by any initial functions.
#' @details
#' @return Exit status
#' @export
#' @examples res = InitBioLink()
#'    res = LoadBioLink(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}

