
library(gridExtra)
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoNTA module
#' @description Initialize ExpoNTA module analysis. It can generate an R6 class object.
#' @usage InitNTA()
#' @param
#' @details ExpoNontarget module is designed to conduct the analysis of the features
#'     from the high-resolution mass spectrometry. It mainly aims to screen and
#'     annotate the significant features associated with the health outcomes.
#' @return An R6 class object.
#' @export
#' @examples res <- InitNTA()
#' @author Mingliang Fang, Bin Wang (corresponding author)

InitNTA = function(){
  url = paste0(urlhead,'InitNTA')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Load data file for ExpoNTA module
#' @description Load data file for ExpoNTA module
#' @usage LoadNTA(PID, UseExample = "default", DataPath=NULL, VocaPath=NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoNTA
#' @param UseExample chr. Method of uploading data. If "default"，user should upload their own data files,
#'    or use "example#1" provided by this module.
#' @param DataPath chr. Input directory of data file, e.g. "D:/test/eg_data_biolink.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @param VocaPath chr. Input directory of vocabulary file, e.g. "D:/test/eg_voca_biolink.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @details
#' @return An R6 class object containing the input data.
#' @export
#' @examples res <- InitNTA()
#'    res = LoadNTA(PID = res$PID, UseExample = "example#1")
#' @author Mingliang Fang, Bin Wang (corresponding author)

LoadNTA =function(PID,
                  UseExample = "default",
                  DataPath = NULL,
                  VocaPath = NULL){
  url = paste0(urlhead,'LoadNTA')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)


    vodata = readxl::read_excel(VocaPath)
  }else{
    exdata = NULL
    vodata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID = PID,
                                         UseExample = UseExample,
                                         Expodata = exdata,
                                         Vocadata = vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}



#' @title Find covariates
#' @description Find covariates
#' @usage FindCovaNta = function(PID, OutPath = "default", VarsY, VarsC_Prior = "default",
#'     VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoNTA
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsC_Prior chr. Potential covariates needing further statistical test.
#'     The default value is all covariate variables listed in the data file.
#' @param VarsC_Fixed chr. Covariate variables fixed in the model by users.
#' @param Method chr. Methods for screening the covariates, including two options,
#'     i.e. "single.factor" and "two.stage".
#' @param Thr num. Threshold of the P-value for screening the covariates. It is
#'     ranging 0.05-0.25. The defaults value is 0.1.
#' @details
#' @return A list containing the selected covariates.
#' @export
#' @examples res <- InitNTA()
#'    res1 = LoadNTA(PID = res$PID, UseExample = "example#1")
#'    res2 = FindCovaNta(PID=res$PID, OutPath = OutPath, VarsY = "Y1",
#'    VarsC_Prior = "default", VarsC_Fixed = "C2",
#'    Method = "single.factor",Thr = 0.1)
#' @author Mingliang Fang, Bin Wang (corresponding author)

FindCovaNta = function(PID,
                       OutPath = "default",
                       VarsY,
                       VarsC_Prior = "default",
                       VarsC_Fixed = NULL,
                       Method = "single.factor",
                       Thr = 0.1){
  if(OutPath == "default"){
    OutPath = getwd()
  }

  if(length(VarsC_Fixed) == 0){
    VarsC_Fixed = ""
  }

  url = paste0(urlhead,'FindCovaNta')
  res = httr::POST(url,
                   body = list(PID=PID,
                               FindCovaNtaVarsY = VarsY,
                               FindCovaNtaVarsC_Prior = VarsC_Prior,
                               FindCovaNtaVarsC_Fixed = VarsC_Fixed,
                               FindCovaNtaMethod = Method,
                               FindCovaNtaThr = Thr),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/NtaCova'))
  df = data.frame(results$Covariables)
  try(
    vroom::vroom_write(df,
                       paste0(OutPath,'/NtaCova/covariates.csv'),
                       delim = ","),
    silent = TRUE
  )
  return(results)
}


#' @title Association analysis
#' @description Association analysis for non-targeted data
#' @usage NtaCros = function(PID,OutPath = "default",VarsY,VarsX = "all.x",
#'     VarsN = "single.factor",FdrCorrect = T,SelMethod = "all",StepwizeThr = 0.1,
#'     RF_ImpThr = 0.9,IncCova = F,Family,RepMsr  = F,Corstr= "ar1")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoNTA
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsX chr. Exposure variable used for modeling. The default option is
#'     "all.x" (All exposure variables are included). Users can also choose available variables.
#'     It should be noted that there is fixed format for the entering characters
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param VarsN chr. Choose the single factor or multiple factor model.
#'     Available options include "single.factor" and "multiple.factor"
#' @param FdrCorrect lgl. T (or TRUE) and F (or FALSE).  Whether to correct the multiple hypotheses by false positive rate (FDR) method.
#' @param SelMethod chr. Methods to select the significant features. Options include
#'     "stepwise" (multiple linear regress using stepwise algorithm),
#'     "lasso" (multiple linear regress using LASSO regularization algorithm),
#'     "random.forest" (random forest), and "all" (combination of the above three method)..
#' @param StepwizeThr num. Threshold of the P value for stepwise regression to
#'     screen important variables. It ranges 0.05-0.25 with the default value of 0.1.
#' @param RF_ImpThr num. Threshold of the total importance for the variables to a random forest model. It ranges 0.5-1.0 with the default value of 0.9.
#' @param IncCova lgl. T (or TRUE) and F (or FALSE). Whether to include the covariate selected in the step of "FindCovaNta".
#' @param Family chr. The link function for the regression model according
#'     the data type of outcomes, including "gaussian" for continuous variable,
#'     "binomial" for binary variable, and "poisson" for counting variable
#' @param RepMsr lgl. T (or TRUE) and F (or FALSE). Whether existing repeated measurement of the subjects.
#' @param Corstr chr. If "RepMsr" = T, the generalized estimating equations (GEE) will be used.
#'     For GEE, three correlation structure options are "exchangeable" "ar1" "unstructured".
#' @details
#' @return A list containing non-target analysis association results
#' @export
#' @examples res <- InitNTA()
#'    res1 = LoadNTA(PID = res$PID, UseExample = "example#1")
#'    res2 = DelNearZeroVar(PID = res$PID) #optional, If run, expotidy package is needed
#'    res3 = DelMiss(PID = res$PID) #optional, If run, expotidy package is needed
#'    res4 = NtaCros(PID=res$PID, VarsY = "Y2", VarsX = "all.x",
#'    VarsN = "multiple.factor", FdrCorrect = "T", SelMethod = "lasso",
#'    StepwizeThr = 0.1, RF_ImpThr = 0.9, IncCova = "F", Family = "binomial",
#'    RepMsr = "F", Corstr = "ar1")
#' @author Mingliang Fang, Bin Wang (corresponding author)

NtaCros = function(PID,
                   OutPath = "default",
                   VarsY,
                   VarsX = "all.x",
                   VarsN = "single.factor",
                   FdrCorrect = T,
                   SelMethod = "all",
                   StepwizeThr = 0.1,
                   RF_ImpThr = 0.9,
                   IncCova = F,
                   Family,
                   RepMsr  = F,
                   Corstr= "ar1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }

  message("It may take some time. Thanks for your patient waiting!")

  url = paste0(urlhead,'NtaCros')
  res = httr::POST(url,
                   body = list(PID=PID,
                               NtaCrosVarsY = VarsY,
                               NtaCrosVarsX = VarsX,
                               NtaCrosVarsN =  VarsN,
                               NtaCrosFdrCorrect = FdrCorrect,
                               NtaCrosSelMethod = SelMethod,
                               NtaCrosStepwizeThr = StepwizeThr,
                               NtaCrosRF_ImpThr = RF_ImpThr,
                               NtaCrosIncCova = IncCova,
                               NtaCrosFamily = Family,
                               NtaCrosRepMsr = RepMsr,
                               NtaCrosCorstr = Corstr),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/NtaCros'))
  for (name in names(results$CrosTable)){
    try(
      vroom::vroom_write(results$CrosTable[[name]],
                         paste0(OutPath,'/NtaCros/', name,".csv"),
                         delim = ","),
      silent = TRUE
    )
  }
  return(results$CrosTable)
}



#' @title Visualize the results of Association analysis
#' @description Visualize the results of Association analysis for non-targeted data
#' @usage VizNtaCros = function(PID, OutPath = "default", VarsY,VarsN, Layout = "volcano",
#'     EffectThr = 0.5, Brightness = "light", Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoNTA
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsN chr. Choose the single factor or multiple factor model.
#'     Available options include "single.factor" and "multiple.factor"
#' @param Layout chr. Visualization layout. Available options include "forest" and "volcano".
#' @param EffectThr num. Threshold of the total importance for the variables to a
#'     random forest model. It ranges 0.5-1.0 with the default value of 0.9.
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'     and several journal preference styles (i.e., cell, nature, science, lancet, nejm, and jama).
#' @details
#' @return A list containing plots of non-target analysis association results
#' @export
#' @examples res <- InitNTA()
#'    res = LoadNTA(PID = res$PID, UseExample = "example#1")
#'    res1 = LoadNTA(PID = res$PID, UseExample = "example#1")
#'    res2 = DelNearZeroVar(PID = res$PID) #optional, If run, expotidy package is needed
#'    res3 = DelMiss(PID = res$PID) #optional, If run, expotidy package is needed
#'    res4 = NtaCros(PID=res$PID, VarsY = "Y2", VarsX = "all.x",
#'    VarsN = "multiple.factor", FdrCorrect = "T", SelMethod = "lasso",
#'    StepwizeThr = 0.1, RF_ImpThr = 0.9, IncCova = "F", Family = "binomial",
#'    RepMsr = "F", Corstr = "ar1")
#' @author Mingliang Fang, Bin Wang (corresponding author)

VizNtaCros = function(PID,
                      OutPath = "default",
                      VarsY,
                      VarsN,
                      Layout = "volcano",
                      EffectThr = 0.5,
                      Brightness = "light",
                      Palette = "default1"
                      ){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizNtaCros')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizNtaCrosVarsY = VarsY,
                               VizNtaCrosVarsN = VarsN,
                               VizNtaCrosLayout = Layout,
                               VizNtaCrosEffectThr = EffectThr,
                               VizNtaCrosBrightness = Brightness,
                               VizNtaCrosPalette = Palette),
                   encode = 'json',
                   httr::timeout(600))
  results = unserialize(httr::content(res))

  for (name in names(results$CrosPlot)){

    try(
      ggplot2::ggsave(paste0(OutPath,'/NtaCros/',name,".png"),
                      plot = results$CrosPlot[[name]],
                      width =  results$CrosPlot_para[[name]][['width']],
                      height = results$CrosPlot_para[[name]][['height']],
                      units = "cm",dpi = 300,
                      limitsize = FALSE),
      silent = TRUE
    )
  }
  return(results$CrosPlot)
}


#' @title Annotate the non-targeted features
#' @description Annotate the non-targeted features
#' @usage NtaAnno = function(PID, OutPath = "default", VarsY, VarsX  = "default",
#'     VarsN  = "single.factor", FdrCorrect = F, AdductPos = "all", AdductNeg = "all",Accuracy)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoNTA
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsX chr. Exposure variable used for modeling. The default option is
#'     "all.x" (All exposure variables are included). Users can also choose available variables.
#'     It should be noted that there is fixed format for the entering characters
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param VarsN chr. Choose the single factor or multiple factor model.
#'     Available options include "single.factor" and "multiple.factor"
#' @param FdrCorrect lgl. T (or TRUE) and F (or FALSE). Whether to correct the
#'     multiple hypotheses by false positive rate (FDR) method.
#' @param AdductPos chr. Adducts formed in the positive mode using LC-MS.
#'     The default is "all", i.e., all the adducts in positive mode will be chosen, including
#'     "M+3ACN+2H,M+ACN+H,M+NH4,M+2ACN+2H,M+2H,M+3H,M+3Na,M+2Na-H,M+ACN+Na,M+H+Na,
#'     M+2K-H,M+H+NH4,2M+K,M+K,2M+NH4,2M+Na,M+2Na,M+DMSO+H,M+2ACN+H,M+IsoProp+Na+H,
#'     M+2H+Na,M+ACN+2H,M+H,2M+H,M+CH3OH+H,M+H+2Na,M+Na,2M+ACN+H,2M+ACN+Na,M+IsoProp+H,M+H+K"
#' @param AdductNeg chr. Adducts formed in the negative mode using LC-MS.
#'     The default is "all", i.e., all the adducts in positive mode will be chosen, including
#'     "M+FA-H,M+Hac-H,M+Br,3M-H,2M+Hac-H,M+K-2H,2M+FA-H,M-H,M-H2O-H,M+Na-2H,
#'     M-2H,M+TFA-H,M+Cl,M-3H,2M-H”
#' @param Accuracy num. Accuracy threshold to match the target compounds. The default is 1 ppm.
#' @details
#' @return A list containing non-target analysis results
#' @export
#' @examples res <- InitNTA()
#'    res = LoadNTA(PID = res$PID, UseExample = "example#1")
#'    res1 = LoadNTA(PID = res$PID, UseExample = "example#1")
#'    res2 = DelNearZeroVar(PID = res$PID) #optional, If run, expotidy package is needed
#'    res3 = DelMiss(PID = res$PID) #optional, If run, expotidy package is needed
#'    res4 = NtaAnno(PID=res$PID,VarsY = "Y1",VarsX = "default",VarsN = "single.factor",
#'    FdrCorrect = "F",AdductPos = "M+H",AdductNeg = "M-H",Accuracy = 1)
#' @author Mingliang Fang, Bin Wang (corresponding author)

NtaAnno = function(PID,
                   OutPath = "default",
                   VarsY,
                   VarsX = "default",
                   VarsN = "single.factor",
                   FdrCorrect = "F",
                   AdductPos = "all",
                   AdductNeg = "all",
                   Accuracy = 5){
  if(OutPath == "default"){
    OutPath = getwd()
  }

  message("It may take some time. Thanks for your patient waiting!")

  url = paste0(urlhead,'NtaAnno')
  res = httr::POST(url,
                   body = list(PID=PID,
                               NtaAnnoVarsY = VarsY,
                               NtaAnnoVarsX = VarsX,
                               NtaAnnoVarsN = VarsN,
                               NtaAnnoFdrCorrect = FdrCorrect,
                               NtaAnnoAdductPos = AdductPos,
                               NtaAnnoAdductNeg = AdductNeg,
                               NtaAnnoAccuracy = Accuracy
                   ),
                   encode = 'json')

  results = unserialize(httr::content(res))

  dir.create(paste0(OutPath,'/NtaAnno'))

  for (name in names(results$AnnoTable)){
    try(
      vroom::vroom_write(results$AnnoTable[[name]],
                         paste0(OutPath,'/NtaAnno/', name,".csv"),
                         delim = ","),
      silent = TRUE
    )
  }
  return(results$AnnoTable)
}



#' @title Visualize annotation results
#' @description Visualize annotation results of non-targeted data
#' @usage VizNtaAnno = function(PID, OutPath = "default", VarsY, VarsN ,Accuracy = 1,
#'     Brightness = "light",Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoNTA
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsN chr. Choose the single factor or multiple factor model.
#'     Available options include "single.factor" and "multiple.factor"
#' @param Accuracy num. Upper limit of accuracy to match the target molecular. The default is 1.
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., cell, nature, science, lancet, nejm, and jama).
#' @details
#' @return A list containing plots of non-target annotation analysis results
#' @export
#' @examples res <- InitNTA()
#'    res = LoadNTA(PID = res$PID, UseExample = "example#1")
#'    res1 = LoadNTA(PID = res$PID, UseExample = "example#1")
#'    res2 = DelNearZeroVar(PID = res$PID) #optional, If run, expotidy package is needed
#'    res3 = DelMiss(PID = res$PID) #optional, If run, expotidy package is needed
#'    res4 = NtaAnno(PID=res$PID,VarsY = "Y1",VarsX = "default",VarsN = "single.factor",
#'    FdrCorrect = "F",AdductPos = "M+H",AdductNeg = "M-H",Accuracy = 1)
#'    res5 = VizNtaAnno(PID=res$PID,OutPath=OutPath,VarsY = "Y1",VarsN = "single.factor",
#'    Accuracy = 1,Brightness = "light",Palette = "default1")
#' @author Mingliang Fang, Bin Wang (corresponding author)

VizNtaAnno = function(PID,
                      OutPath = "default",
                      VarsY,
                      VarsN,
                      Accuracy = 1,
                      Brightness = "light",
                      Palette = "default1"
                      ){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizNtaAnno')
  res = httr::POST(url,
                   body = list(PID=PID,
                               VizNtaAnnoVarsY = VarsY,
                               VizNtaAnnoVarsN = VarsN,
                               VizNtaAnnoAccuracy = Accuracy,
                               VizNtaAnnoBrightness = Brightness,
                               VizNtaAnnoPalette = Palette
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))

  for (name in names(results$AnnoPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/NtaAnno/',name,".png"),
                      plot = results$AnnoPlot[[name]],
                      width =  15,
                      height = 15,
                      units = "cm",dpi = 300),
      silent = TRUE
    )
  }
  return(results$AnnoPlot)
}



#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by any initial functions.
#' @details
#' @return Exit status
#' @export
#' @examples res = InitBioLink()
#'    res = LoadBioLink(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}




