
library(gridExtra)
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoMixEffect module
#' @description Initialize ExpoMixEffect module analysis. It can generate an R6 class object.
#' @usage InitMix()
#' @param 
#' @details ExpoMixEffect module is designed to analyze mixture effect of the various 
#'     exposure factors. It mainly aims to screen the representative features with 
#'     high contribution to the health outcome, as well as their potential interaction effect. 
#' @return An R6 class object.
#' @export
#' @examples res <- InitMix()
#' @author Bin Wang (corresponding author)

InitMix = function(){
  url = paste0(urlhead,'InitMix')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum = seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Load data file for ExpoMixEffect module
#' @description Load data file for ExpoMixEffect module
#' @usage LoadMix(PID, UseExample = "default", DataPath = NULL, VocaPath = NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoMixEffect
#' @param UseExample chr. Method of uploading data. If "default"，user should upload their own data files, 
#'    or use "example#1" provided by this module. 
#' @param DataPath chr. Input directory of data file, e.g. "D:/test/eg_data_biolink.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @param VocaPath chr. Input directory of vocabulary file, e.g. "D:/test/eg_voca_biolink.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @details 
#' @return An R6 class object containing the input data.
#' @export
#' @examples res <- InitMix()
#'    res = LoadMix(PID = res$PID, UseExample = "example#1")
#' @author Bin Wang 

LoadMix = function(PID,
                   UseExample = "default",
                   DataPath = NULL,
                   VocaPath = NULL){
  url = paste0(urlhead,'LoadMix')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)

    vodata = readxl::read_excel(VocaPath)
  }else{
    exdata = NULL
    vodata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID = PID,
                                         UseExample = UseExample,
                                         Expodata = exdata,
                                         Vocadata = vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Find covariates
#' @description Find covariates
#' @usage FindCovaMix = function(PID, OutPath = "default", VarsY, VarsC_Prior = "default", 
#'     VarsC_Fixed = NULL, Method = "single.factor", Thr = 0.1)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoMixEffect 
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsC_Prior chr. Potential covariates needing further statistical test. 
#'     The default value is all covariate variables listed in the data file. 
#' @param VarsC_Fixed chr. Covariate variables fixed in the model by users.
#' @param Method chr. Methods for screening the covariates, including two options, 
#'     i.e. "single.factor" and "two.stage".
#' @param Thr num. Threshold of the P-value for screening the covariates. It is 
#'     ranging 0.05-0.25. The defaults value is 0.1. 
#' @details 
#' @return A list containing the selected covariates.
#' @export
#' @examples res <- InitMix()
#'    res = LoadMix(PID = res$PID, UseExample = "example#1")
#' @author Bin Wang 

FindCovaMix = function(PID,
                       OutPath = "default",
                       VarsY,
                       VarsC_Prior = "default",
                       VarsC_Fixed = NULL,
                       Method = "single.factor",
                       Thr = 0.1){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  if(length(VarsC_Fixed) == 0){
    VarsC_Fixed = ""
  }
  
  url = paste0(urlhead,'FindCovaMix')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VarsY = VarsY,
                               VarsC_Prior = VarsC_Prior,
                               VarsC_Fixed = VarsC_Fixed,
                               Method = Method,
                               Thr = Thr),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/MixCova'))
  df = data.frame(results$MixCovariables)
  try(
    vroom::vroom_write(df,
                       paste0(OutPath,'/MixCova/mix_covariates.csv'),
                       delim = ","),
    silent = TRUE
  )
  return(results)
}



#' @title Build multiple linear regression (MLR) model
#' @description Build multiple linear regression (MLR) model
#' @usage MixMLR = function(PID,OutPath = "default",VarsY,VarsX,IncCova = "F",
#'     SelMethod = "lasso",PredType = "response",Family)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoMixEffect 
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsX chr. Exposure variable used for modeling. The default option is 
#'     "all.x" (All exposure variables are included). Users can also choose available variables. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param IncCova lgl. T (or TRUE) and F (or FALSE). Whether to include the covariate 
#'     selected in the function "FindCovaMix"
#' @param SelMethod chr. Method to select the important features to the final model. 
#'     Options include "stepwise" (stepwise regression), "lasso" (Regularization regression of 
#'     least absolute shrinkage and selection operator), and "enet" (Regularization regression of elastic net).
#' @param PredType chr. Prediction type of the outcome variable, including "response" 
#'     for the actual values and "prob" for outcome with binary variable.
#' @param Family chr. The link function for the regression model according the data type of outcomes, 
#'     including "gaussian" for continuous variable, "binomial" for binary variable, 
#'     and "poisson" for counting variable
#' @details 
#' @return A list containing the MLR analysis.
#' @export
#' @examples res <- InitMix()
#'    res1 = LoadMix(PID = res$PID, UseExample = "example#1")
#'    res2 = MixMLR(PID = res$PID, VarsY = "Y1", VarsX = "all.x", IncCova = "F", 
#'    SelMethod = "lasso", PredType = "response", Family = "gaussian")
#' @author Bin Wang 

MixMLR = function(PID,
                  OutPath = "default",
                  VarsY,
                  VarsX,
                  IncCova = "F",
                  SelMethod = "lasso",
                  PredType = "response",
                  Family){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'MixMLR')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VarsY = VarsY,
                               VarsX = VarsX,
                               IncCova = IncCova,
                               SelMethod = SelMethod,
                               PredType = PredType,
                               Family = Family),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/MixMLR'))
  for(name in names(results$MLRTable)){
    try(
      vroom::vroom_write(results$MLRTable[[name]],
                         paste0(OutPath,'/MixMLR/', name,".csv"),
                         delim = ","),silent = TRUE
    )
  }
  
  return(results$MLRTable)
}



#' @title Visualize the model results
#' @description Visualize the results of multiple linear regression (MLR) model
#' @usage VizMixMLR = function(PID,OutPath = "default",VarsY,SelMethod,Brightness = "light",Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoMixEffect 
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param SelMethod chr. Method to select the important features to the final model. 
#'     Options include "stepwise" (stepwise regression), "lasso" (Regularization regression of 
#'     least absolute shrinkage and selection operator), and "enet" (Regularization regression of elastic net).
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".  
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., cell, nature, science, lancet, nejm, and jama). 
#' @details 
#' @return A list containing the MLR analysis plot.
#' @export
#' @examples res <- InitMix()
#'    res1 = LoadMix(PID = res$PID, UseExample = "example#1")
#'    res2 = MixMLR(PID = res$PID, VarsY = "Y1", VarsX = "all.x",
#'    IncCova = "F", SelMethod = "lasso", PredType = "response", Family = "gaussian")
#'    res3 = VizMixMLR(PID=res$PID, VarsY = "Y1", SelMethod = 'lasso',
#'    Brightness = "light", Palette = "default1")
#' @author Bin Wang 

VizMixMLR = function(PID,
                     OutPath = "default",
                     VarsY,
                     SelMethod,
                     Brightness = "light",
                     Palette = "default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  message("It may take some time. Thanks for your patient waiting!")
  
  url = paste0(urlhead,'VizMixMLR')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VizVarsY = VarsY,
                               SelMethod = SelMethod,
                               Brightness = Brightness,
                               Palette = Palette),
                   encode = 'json',
                   httr::timeout(600))
  results = unserialize(httr::content(res))

  for (name in names(results$MLRPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/MixMLR/',name,".png"),
                      plot = results$MLRPlot[[name]],
                      width =  results$MLRPlot_para[[name]][['width']],
                      height = results$MLRPlot_para[[name]][['height']],
                      units = "cm",dpi = 300),silent = TRUE
    )
  }
  return(results$MLRPlot)
}



#' @title Build weighted quantile sum regression (WQS) model
#' @description Build weighted quantile sum regression (WQS) model
#' @usage MixWQS(PID, OutPath = "default", VarsY, VarsX, IncCova = "F", Family,
#'     VarStrat = "none",RatioValidat = 0.3,q = 10,b = 100,b1_pos = F,b1_constr = F)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoMixEffect
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsX chr. Exposure variable used for modeling. The default option is 
#'     "all.x" (All exposure variables are included). Users can also choose available variables. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param IncCova lgl. T (or TRUE) and F (or FALSE). Whether to include the covariate 
#'     selected in the function "FindCovaMix" 
#' @param Family chr. The link function for the regression model according the data type of outcomes, 
#'     including "gaussian" for continuous variable, "binomial" for binary variable, 
#'     and "poisson" for counting variable.
#' @param VarStrat chr. A factor variable used for stratifying for the model.
#' @param RatioValidat num. Percentage of the dataset to be used to validate the model. 
#'     If validation = 0 then the test dataset is used as validation dataset too. The default is 0.3.
#' @param q num. Levels for ranking mixture variables, e.g. in quartiles (q = 4), deciles (q = 10), 
#'     or percentiles (q = 100). The default is 10.
#' @param b num. Number of bootstrap samples used in parameter estimation. The default is 100.
#' @param b1_pos lgl. T (or TRUE) and F (or FALSE). Whether the beta values were positive 
#'     to derive weights from to build models.
#' @param b1_constr lgl. T (or TRUE) and F (or FALSE). A logial value that determines 
#'     whether to apply positive (if b1_pos = TRUE) or negative (if b1_pos = FALSE) constraints 
#'     in the optimization function for the weight estimation.
#' @details 
#' @return A list containing the WQS analysis results.
#' @export
#' @examples res <- InitMix()
#'    res1 = LoadMix(PID = res$PID, UseExample = "example#1")
#'    res3 = MixWQS(PID=res$PID, VarsY = "Y1", VarsX = "all.x", IncCova = "F",
#'    Family = "gaussian", VarStrat = "none", RatioValidat = 0.3,
#'    q = 10, b=100, b1_pos = 'F', b1_constr = 'F')
#' @author Bin Wang 

MixWQS = function(PID,
                  OutPath = "default",
                  VarsY,
                  VarsX,
                  IncCova = "F",
                  Family,
                  VarStrat = "none",
                  RatioValidat = 0.3,
                  q = 10,
                  b = 100,
                  b1_pos = F,
                  b1_constr = F){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'MixWQS')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VarsY = VarsY,
                               VarsX = VarsX,
                               IncCova = IncCova,
                               Family = Family,
                               VarStrat = VarStrat,
                               RatioValidat = RatioValidat,
                               q = q,
                               b = b,
                               b1_pos = b1_pos,
                               b1_constr = b1_constr
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/MixWQS'))
  for(name in names(results$WQSTable)){
    try(
      vroom::vroom_write(results$WQSTable[[name]],
                         paste0(OutPath,'/MixWQS/', name,".csv"),
                         delim = ","),silent = TRUE
    )
  }
  return(results$WQSTable)
}


#' @title Visualize results of weighted quantile sum regression (WQS) model
#' @description Visualize results of weighted quantile sum regression (WQS) model
#' @usage VizMixWQS(PID, OutPath = "default", VarsY, Brightness  = "dark", Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoMixEffect
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".  
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., cell, nature, science, lancet, nejm, and jama). 
#' @details 
#' @return A list containing the WQS analysis results' plot.
#' @export 
#' @examples res <- InitMix()
#'    res1 = LoadMix(PID = res$PID, UseExample = "example#1")
#'    res2 = MixWQS(PID=res$PID, VarsY = "Y1", VarsX = "all.x",
#'    IncCova = "F",Family = "gaussian", VarStrat = "none", RatioValidat = 0.3,
#'    q = 10, b=100, b1_pos = 'F', b1_constr = 'F')
#'    res3 = VizMixWQS(PID = res$PID,  VarsY = "Y1", 
#'    Brightness = "dark",Palette = "default1")
#' @author Bin Wang 

VizMixWQS = function(PID,
                     OutPath = "default",
                     VarsY,
                     Brightness  = "dark",
                     Palette = "default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  message("It may take some time. Thanks for your patient waiting!")
  
  url = paste0(urlhead,'VizMixWQS')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VizVarsY = VarsY,
                               Brightness = Brightness,
                               Palette = Palette
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))

  for (name in names(results$WQSPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/MixWQS/',name,".png"),
                      plot = results$WQSPlot[[name]],
                      width = 35,
                      height = 20,
                      units = "cm",dpi = 300),silent = TRUE
    )
  }
  return(results$WQSPlot)
}


#' @title Build the Bayesian Kernel Machine Regression (BKMR) model
#' @description Build the Bayesian Kernel Machine Regression (BKMR) model
#' @usage MixBKMR = function(PID, OutPath = "default", VarsY, VarsX, IncCova, 
#'     Family, Group = F,Iter = 2000, qfixed = 0.5, qsbivar = "default",
#'     qsoverall = "default", qsdiff = "default")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoMixEffect
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param VarsX chr. Exposure variable used for modeling. The default option is 
#'     "all.x" (All exposure variables are included). Users can also choose available variables. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "X1,X2,X3"
#' @param IncCova lgl. T (or TRUE) and F (or FALSE). Whether to include the covariate 
#'     selected in the function "FindCovaMix"
#' @param Family chr. The link function for the regression model according the data type of outcomes, 
#'     including "gaussian" for continuous variable, "binomial" for binary variable, 
#'     and "poisson" for counting variable
#' @param Group lgl. T (or TRUE) and F (or FALSE). Whether to use group indicators 
#'     for fitting hierarchical variable selection. If "TRUE", the group name (GroupName) 
#'     should be provided in the vocabulary data file.
#' @param Iter num. Number of iterations for modeling. The default is 500. 
#'     For more accurate and stable results, a minimum of 10,000 iteration is recommended.
#' @param qfixed num. Quantile at which to fix the other predictors. The default is 0.5.
#' @param qsbivar chr. Quantiles at which to fix the second variable. It should be noted that 
#'     there is fixed format for the entering characters separated with comma and without space,
#'     e.g., the default character sequence is "0.1,0.5,0.9"
#' @param qsoverall num. Quantiles at which to calculate the overall risk summary. It should be noted that 
#'     there is fixed format for the entering characters separated with comma and without space,
#'     e.g., the default character sequence is "0.25,0.30,0.35,0.40,0.45,0.50,0.55,0.60,0.65,0.70,0.75"
#' @param qsdiff chr. Indicating the two quantiles for computing their effect difference. It should be noted that 
#'     there is fixed format for the entering characters separated with comma and without space,
#'     e.g., the default character sequence is "0.25,0.75".
#' @details 
#' @return A list containing the BKMR analysis results.
#' @export
#' @examples res <- InitMix()
#'    res1 = LoadMix(PID = res$PID, UseExample = "example#1")
#'    res2 = MixBKMR(PID = res$PID, VarsY = "Y1", VarsX = "X4,X5,X6,X7,X8,X9,X10", 
#'    IncCova = 'F', Family = "gaussian", Group = 'F',Iter = 2000,qfixed = 0.5,qsbivar = "default", 
#'    qsoverall = "default",qsdiff = "default")
#' @author Bin Wang 

MixBKMR = function(PID,
                   OutPath = "default",
                   VarsY,
                   VarsX,
                   IncCova,
                   Family,
                   Group = F,
                   Iter = 2000,
                   qfixed = 0.5,
                   qsbivar = "default",
                   qsoverall = "default" ,
                   qsdiff = "default"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'MixBKMR')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VarsY = VarsY,
                               VarsX = VarsX,
                               IncCova = IncCova,
                               Family = Family,
                               Group = Group,
                               Iter = Iter,
                               qfixed = qfixed,
                               qsbivar = qsbivar,
                               qsoverall = qsoverall,
                               qsdiff = qsdiff
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/MixBKMR'))
  for(name in names(results$TableBKMR)){
    try(
      vroom::vroom_write(results$TableBKMR[[name]],
                         paste0(OutPath,'/MixBKMR/', name,".csv"),
                         delim = ","),silent = TRUE
    )
  }
  return(results$TableBKMR)
}


#' @title Visualize the model results of Bayesian Kernel Machine Regression (BKMR)
#' @description Visualize the model results of Bayesian Kernel Machine Regression (BKMR)
#' @usage VizMixBKMR = function(PID, OutPath = "default", VarsY, Brightness = "dark", Palette = "default1")
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoMixEffect 
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param VarsY chr. Outcome variable used for modeling. Only one variable can be entered.
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".  
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., cell, nature, science, lancet, nejm, and jama). 
#' @details 
#' @return A list containing the BKMR analysis results' plot.
#' @export
#' @examples res <- InitMix()
#'    res1 = LoadMix(PID = res$PID, UseExample = "example#1")
#'    res2 = MixBKMR(PID = res$PID, VarsY = "Y1", VarsX = "X4,X5,X6,X7,X8,X9,X10", 
#'    IncCova = 'F', Family = "gaussian", Group = 'F',Iter = 2000,qfixed = 0.5,
#'    qsbivar = "default", qsoverall = "default",qsdiff = "default")
#'    res3 = VizMixBKMR(PID=res$PID, VarsY = "Y1",Brightness = "dark",Palette = "default1")
#' @author Bin Wang 

VizMixBKMR = function(PID,
                      OutPath = "default",
                      VarsY,
                      Brightness = "dark",
                      Palette = "default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  message("It may take some time. Thanks for your patient waiting!")
  
  url = paste0(urlhead,'VizMixBKMR')
  res = httr::POST(url,
                   body = list(PID = PID,
                               VizVarsY = VarsY,
                               Brightness = Brightness,
                               Palette = Palette
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))

  for (name in names(results$BKMRPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/MixBKMR/',name,".png"),
                      plot = results$BKMRPlot[[name]],
                      width =  results$BKMRPlot_para[[name]][['width']],
                      height = results$BKMRPlot_para[[name]][['height']],
                      units = "cm"),silent = TRUE
    )
  }
  return(results$BKMRPlot)
}


#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by any initial functions.
#' @details 
#' @return Exit status
#' @export
#' @examples res = InitBioLink()
#'    res = LoadBioLink(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID = PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}



