library(gridExtra)

urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoStat Module.
#' @description The first step to start ExpoStat Module.
#' @usage InitStat().
#' @return An R6 class object.
#' @export
#' @examples res = InitStat()
#' @author Yanqiu Feng, Bin Wang (corresponding author)

InitStat = function(){
  url = paste0(urlhead,'InitStat')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Load data for ExpoStat Module.
#' @description Upload  data file for ExpoStat Module.
#' @usage LoadStat(PID, UseExample = "default", DataPath = NULL, VocaPath = NULL).
#' @param PID chr. Program ID. It must be the same with the PID generated by InitStat.
#' @param UseExample chr. Whether uses example data for analyses, available option include "example#1"
#'    for using example data1 and "default" for using data.
#' @param DataPath chr. Input file directory, e.g. "D:/test/expostat_data.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @param VocaPath chr. Input file directory, e.g. "D:/test/expostat_voca.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @return A list object containing imported data.
#' @export
#' @examples res = InitStat()
#'    res1 = LoadStat(PID = res$PID, UseExample = "example#1")
#'    res2 = LoadStat(PID = res$PID, UseExample = "default", DataPath = "D:/test/expostat_data.xlsx", VocaPath = "D:/test/expostat_voca.xlsx")
#' @author Yanqiu Feng, Bin Wang (corresponding author)

LoadStat =function(PID,
                   UseExample="default",
                   DataPath=NULL,
                   VocaPath=NULL){
  url = paste0(urlhead,'LoadStat')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)

    vodata = readxl::read_excel(VocaPath)
  }else{
    exdata = NULL
    vodata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID=PID,
                                         UseExample=UseExample,
                                         Expodata=exdata,
                                         Vocadata=vodata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Create Table 1 for ExpoStat Module.
#' @description Create Table 1 for different epidemilogical study designs.
#' @usage StatTable1(PID = res$PID,EpiDesign = "cohort", Group = 'T', VarsY = "Y1", VarsC = "C1,C2,C3,C4,C5,C6",
#'    Missing = "ifany").
#' @param PID chr. Program ID. It must be the same with the PID generated by InitStat.
#' @param OutPath chr. Output file directory, e.g. "D:/ExpoStat/StatTable1". It should be
#'    noted that the slash symbol is "/", not "\".If "default", the current working directory will be set.
#' @param EpiDesign chr. Research types provided for users, include "cohort" , "case-control", "cross-section".
#' @param Group lgl. Whether to separate dataset into train and test data for creating Table 1. The default is "TRUE".
#' @param VarsY chr. Outcome variable used for modelling. Only one variable can be entered.
#' @param VarsC chr. Covariate variables needing further statistical test.  It should be noted that there is fixed format for
#'     the entering characters separated with  "," and without space. The defaults value is all covariate variables listed in the
#'     data file, which can be entered with "all.c".
#' @param Missing chr. Counts of missing values in the table, available options include are "no" (never display missing values),
#'    "ifany" (only display if any missing values), and "always" (includes missing count row for all variables). Default is "ifany".
#' @return A list object containing standardized table 1
#' @export
#' @examples res = InitStat()
#'    res1 = LoadStat(PID = res$PID, UseExample = "example#1")
#'    res2 = StatTable1(PID = res$PID, EpiDesign = "cohort" , Group = 'T', VarsY = "Y1", VarsC = "C1,C2,C3,C4,C5,C6", Missing = "ifany")
#' @author Yanqiu Feng, Bin Wang (corresponding author)

StatTable1 = function(PID,
                      OutPath="default",
                      EpiDesign,
                      Group,
                      VarsY,
                      VarsC,
                      Missing){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'StatTable1')
  res = httr::POST(url,
                   body = list(PID=PID,
                               StatTable1EpiDesign=EpiDesign,
                               StatTable1Group=Group,
                               StatTable1VarsY=VarsY,
                               StatTable1VarsC=VarsC,
                               StatTable1Missing=Missing),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/StatTable1'))
  for (name in names(results$Stat_Table1)){
    try(
      gt::gtsave(data=results$Stat_Table1[[name]],
                 filename = paste0(OutPath,'/StatTable1/',name)),
      silent = TRUE
    )
  }

  return(results)
}


#' @title Normality test.
#' @description Normality test for numeric variables.
#' @usage StatNorm(PID = res$PID,Group = T, Vars = 'X5,X6,X7,X8,X9', Method = "shapiro.test", Layout = "rose.chart" ,
#'    Brightness = "light", Palette = "default3").
#' @param PID chr. Program ID. It must be the same with the PID generated by InitStat.
#' @param OutPath chr. Output file directory, e.g. "D:/ExpoStat/StatNorm". It should be
#'    noted that the slash symbol is "/", not "\".If "default", the current working directory will be set.
#' @param Group lgl. Whether to separate dataset into train and test data for normality test. The default is "TRUE".
#' @param Vars chr. Target variables used for modelling. It should be noted that there is fixed format for the entering characters
#'    separated with  "," and without space. The default values is "all" (all variables are included).
#' @param Method chr. Normality test method. Only "shapiro.test" method is available at present.
#' @param Layout chr. Visualization layout. Available values include "column", "column.points", "rose.chart", and "density".
#' @param Brightness chr. Visualization brightness.  Available values include "light" and "dark".
#' @param Palette chr. Visualization palette. Available values include "default1", "default2", "default3" and 5  journal option
#'    including "cell", "nature", "science", "lancet", "nejm".
#' @return A list object containing the results of normality test for variables and  visualization of the results.
#' @export
#' @examples res = InitStat()
#'    res1 = LoadStat(PID = res$PID, UseExample = "example#1")
#'    res2 = StatNorm(PID=res$PID, Group = T, Vars = 'X5,X6,X7,X8,X9', Method = "shapiro.test", Layout = "rose.chart" , Brightness = "light", Palette = "default3")
#' @author Yanqiu Feng, Bin Wang (corresponding author)

StatNorm = function(PID,
                    OutPath="default",
                    Group,
                    Vars,
                    Method,
                    Layout,
                    Brightness,
                    Palette){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'StatNorm')
  res = httr::POST(url,
                   body = list(PID=PID,
                               StatNormGroup=Group,
                               StatNormVars=Vars,
                               StatNormMethod=Method,
                               StatNormLayout=Layout,
                               StatNormBrightness=Brightness,
                               StatNormPalette=Palette
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))

  dir.create(paste0(OutPath,'/StatNorm'))
  for (name in names(results$normtable)){
    try(
      vroom::vroom_write(results$normtable[[name]],
                         paste0(OutPath,'/StatNorm/', name,".csv"),
                         delim = ","),silent = TRUE
    )
  }

  for (name in names(results$NormPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/StatNorm/',name,".jpg"),
                      plot = results$NormPlot[[name]],
                      width =  results$NormPlot_para[[name]][['width']],
                      height = results$NormPlot_para[[name]][['height']],
                      units = "cm"),silent = TRUE
    )
  }

  return(results)
}


#' @title Extreme value calculation.
#' @description Extreme value calculation for numeric variables.
#' @usage StatExtre(PID=res$PID, Group = T, Vars = "X5,X6,X7,X8,X9", LimitLow = 0.025, LimitUpper = 0.975, Layout = "column.points",
#'    Brightness = "light", Palette = "default2").
#' @param PID chr. Program ID. It must be the same with the PID generated by InitStat.
#' @param OutPath chr. Output file directory, e.g. "D:/ExpoStat/StatExtre". It should be
#'    noted that the slash symbol is "/", not "\".If "default", the current working directory will be set.
#' @param Group lgl. Whether to separate dataset into train and test data for normality test. The default is "TRUE".
#' @param Vars chr. Target variables used for modelling. It should be noted that there is fixed format for the entering characters
#'    separated with  "," and without space. The default values is "all" (all variables are included).
#' @param LimitLow num. Lower limit ratio to screen the small extreme values located from 0 to this lower limit of the target variables.
#' @param LimitUpper num. Upper limit ratio to screen the large extreme values located from this lower limit to 1 of the target variables.
#' @param Layout chr. Visualization layout . Available values include "column.points", "heatmap".
#' @param Brightness chr. Visualization brightness . Available values include "light" and "dark".
#' @param Palette chr. Visualization palette . Available values include "default1", "default2", "default3" and 5  journal option
#'    including "cell", "nature", "science", "lancet", "nejm".
#' @return A list object containing the results of extremum for variables and  visualization of the results.
#' @export
#' @examples res = InitStat()
#'    res1 = LoadStat(PID = res$PID, UseExample = "example#1")
#'    res2 = StatExtre(PID = res$PID, Group = T, Vars = "X5,X6,X7,X8,X9", LimitLow = 0.025, LimitUpper = 0.975, Layout = "column.points", Brightness = "light", Palette = "default2")
#' @author Yanqiu Feng, Bin Wang (corresponding author)

StatExtre = function(PID,
                     OutPath="default",
                     Group,
                     Vars,
                     LimitLow,
                     LimitUpper,
                     Layout,
                     Brightness,
                     Palette){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'StatExtre')
  res = httr::POST(url,
                   body = list(PID=PID,
                               StatExtreGroup=Group,
                               StatExtreVars =Vars,
                               StatExtreLimitLow = LimitLow,
                               StatExtreLimitUpper = LimitUpper,
                               StatExtreLayout =Layout,
                               StatExtreBrightness = Brightness,
                               StatExtrePalette = Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/StatExtre'))
    try(
      vroom::vroom_write(results$Extretable,
                         paste0(OutPath,'/StatExtre/StatExtre.csv'),
                         delim = ","),silent = TRUE
    )

  for (name in names(results$ExtrePlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/StatExtre/',name,".jpg"),
                      plot = results$ExtrePlot[[name]],
                      width =  results$ExtrePlot_para[[name]][['width']],
                      height = results$ExtrePlot_para[[name]][['height']],
                      units = "cm"),silent = TRUE
    )
  }
  return(results)
}


#' @title Variable description.
#' @description Calculate median, mean .etc for numeric variables,frequency and count for Discrete variable.
#' @usage StatDesc(PID=res$PID,Group = F, Vars = "C1,C2,X5,X6,X7,X8,X9", VarsBy = "Y1", Layout = "box" , Brightness = "dark" ,
#'    Palette ="science").
#' @param PID chr. Program ID. It must be the same with the PID generated by InitStat.
#' @param OutPath chr. Output file directory, e.g. "D:/ExpoStat/StatDesc". It should be
#'    noted that the slash symbol is "/", not "\".If "default", the current working directory will be set.
#' @param Group lgl. Whether to separate dataset into train and test data for normality test. The default is "TRUE".
#' @param Vars chr. Target variables used for modelling. It should be noted that there is fixed format for the entering characters
#'    separated with  "," and without space. The default values is "all" (all variables are included).
#' @param VarsBy chr. Variable used to group the observation for size description.
#' @param Layout chr. Visualization layout. Available values include "box", "violin".
#' @param Brightness chr. Visualization brightness. Available values include "light" and "dark".
#' @param Palette chr. Visualization palette. Available values include "default1", "default2" and 5  journal option
#'    including "cell", "nature", "science", "lancet", "nejm".
#' @return A list object containing the results of variable description for continuous and discrete variables respectively
#'    and  visualization of the continuous variables.
#' @export
#' @examples res = InitStat()
#'    res1 = LoadStat(PID = res$PID, UseExample = "example#1")
#'    res2 = StatDesc(PID = res$PID, Group = T, Vars = "C1,C2,X5,X6,X7,X8,X9", VarsBy = NULL, Layout = "box", Brightness = "light", Palette = "default2")
#' @author Yanqiu Feng, Bin Wang (corresponding author)

StatDesc = function(PID,
                    OutPath="default",
                    Group,
                    Vars,
                    VarsBy,
                    Layout,
                    Brightness,
                    Palette){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'StatDesc')
  res = httr::POST(url,
                   body = list(PID=PID,
                               StatDescGroup=Group,
                               StatDescVars=Vars,
                               StatDescVarsBy=VarsBy,
                               StatDescLayout=Layout,
                               StatDescBrightness=Brightness,
                               StatDescPalette=Palette
                   ),
                   encode = 'json',
                   httr::timeout(600))
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/StatDesc'))
  for (name in names(results$Desctable)){
    try(
      vroom::vroom_write(results$Desctable[[name]],
                         paste0(OutPath,'/StatDesc/',name,'.csv'),
                         delim = ","),silent = TRUE
    )
  }

  for (name in names(results$DescPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/StatDesc/',name,".jpg"),
                      plot = results$DescPlot[[name]],
                      width =  results$DescPlot_para[[name]][['width']],
                      height = results$DescPlot_para[[name]][['height']],
                      units = "cm"),silent = TRUE
    )
  }
  return(results)
}


#' @title Size comparison for groups.
#' @description Perform size comparisons between groups.
#' @usage StatComp(PID = res$PID,Group = T, Task = "mean", Vars = "X5,X6,X7,X8,X9", VarsBy = "Y1" , Method = "wilcox",
#'    Layout = "density" , Brightness = "dark" , Palette = "default3").
#' @param PID chr. Program ID. It must be the same with the PID generated by InitStat.
#' @param OutPath chr. Output file directory, e.g. "D:/ExpoStat/StatComp". It should be
#'    noted that the slash symbol is "/", not "\".If "default", the current working directory will be set.
#' @param Group lgl. Whether to separate dataset into train and test data for normality test. The default is "TRUE".
#' @param Task chr. Comparison task. At present, only the mean comparison is available.
#' @param Vars chr. Target variables used for modelling. It should be noted that there is fixed format for the entering
#'    characters separated with  "," and without space. The default values is "all" (all variables are included).
#' @param VarsBy chr. Variable  used to group the observation for size comparison.
#' @param Method chr. Comparison method. At present, only "wilcox" (Wilcoxon rank sum test) is available.
#' @param Layout chr. Visualization layout. Available values include "column.points", "density".
#' @param Brightness chr. Visualization brightness. Available values include "light" and "dark".
#' @param Palette chr. Visualization palette. Available values include "default1", "default2" , "default3" and 5  journal option
#'    including "cell", "nature", "science", "lancet", "nejm".
#' @return A list object containing the results of size comparisons between groups for variables and  visualization of the results.
#' @export
#' @examples res = InitStat()
#'    res1 = LoadStat(PID = res$PID, UseExample = "example#1")
#'    res2 = StatComp(PID=res$PID, Group = T, Task = "mean", Vars = "X5,X6,X7,X8,X9", VarsBy = "Y1", Method = "wilcox", Layout = "density" , Brightness = "dark" , Palette = "default3")
#' @author Yanqiu Feng, Bin Wang (corresponding author)

StatComp = function(PID,
                    OutPath="default",
                    Group,
                    Task= "mean",
                    Vars,
                    VarsBy,
                    Method= "wilcox",
                    Layout,
                    Brightness,
                    Palette){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'StatComp')
  res = httr::POST(url,
                   body = list(PID=PID,
                               StatCompGroup =Group,
                               StatCompTask =Task,
                               StatCompVars =Vars,
                               StatCompVarsBy =VarsBy,
                               StatCompMethod =Method,
                               StatCompLayout =Layout,
                               StatCompBrightness =Brightness,
                               StatCompPalette = Palette
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/StatComp'))
  for (name in names(results$Comptable)){
    try(
      vroom::vroom_write(results$Comptable[[name]],
                         paste0(OutPath,'/StatComp/',name,'.csv'),
                         delim = ","),silent = TRUE
    )
  }

  for (name in names(results$CompPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/StatComp/',name,".jpg"),
                      plot = results$CompPlot[[name]],
                      width =  results$CompPlot_para[[name]][['width']],
                      height = results$CompPlot_para[[name]][['height']],
                      units = "cm"),silent = TRUE
    )
  }
  return(results)
}


#' @title Correlation analysis.
#' @description Perform correlation analysis between variables.
#' @usage StatCorr(PID = res$PID,Group = T, VarsX = "X5,X6,X7,X8,X9", VarsY = "Y1", VarsBy = "Y1", Method = "pearson",
#'    Layout = "bubble", Brightness = "dark", Palette = "nature").
#' @param PID chr. Program ID. It must be the same with the PID generated by InitStat.
#' @param OutPath chr. Output file directory, e.g. "D:/ExpoStat/StatCorr". It should be
#'    noted that the slash symbol is "/", not "\".If "default", the current working directory will be set.
#' @param Group lgl. Whether to separate dataset into train and test data for normality test. The default is "TRUE".
#' @param VarsX chr. Target variables used for modelling. It should be noted that there is fixed format for the entering
#'    characters separated with  "," and without space. The default values is "all.x" (all variables are included).
#' @param VarsY chr. Target outcome variables used for correlation analysis.
#' @param VarsBy chr. Variable  used to group the observation for correlation analysis.
#' @param Method chr.  Method for orrelation analysis. Available values include "spearman" (Spearman's rank correlation analysis)
#'    and "pearson" (Pearson correlation analysis).
#' @param Layout chr. Visualization layout. Available values include "heatmap", "bubble", "matrix".
#' @param Brightness chr. Visualization brightness. Available values include "light" and "dark".
#' @param Palette chr. Visualization palette. Available values include "default1", "default2" , "default3" and 5  journal option
#'    including "cell", "nature", "science", "lancet", "nejm".
#' @return A list object containing the results of correlation analysis between variables and  visualization of the results.
#' @export
#' @examples res = InitStat()
#'    res1 = LoadStat(PID = res$PID, UseExample = "example#1")
#'    res2 = StatCorr(PID = res$PID, Group = T, VarsX = "X5,X6,X7,X8,X9", VarsY = "Y1", VarsBy = "Y1", Method = "pearson", Layout = "bubble", Brightness = "dark", Palette = "nature")
#' @author Yanqiu Feng, Bin Wang (corresponding author)

StatCorr = function(PID,
                    OutPath="default",
                    Group,
                    VarsX,
                    VarsY,
                    VarsBy,
                    Method,
                    Layout,
                    Brightness,
                    Palette){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'StatCorr')
  res = httr::POST(url,
                   body = list(PID=PID,
                               StatCorrGroup =Group,
                               StatCorrVarsX =VarsX,
                               StatCorrVarsY =VarsY,
                               StatCorrVarsBy =VarsBy,
                               StatCorrMethod =Method,
                               StatCorrLayout =Layout,
                               StatCorrBrightness =Brightness,
                               StatCorrPalette = Palette
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/StatCorr'))
  for (name in names(results$Corrtable)){
    try(
      vroom::vroom_write(results$Corrtable[[name]],
                         paste0(OutPath,'/StatCorr/',name,'.csv'),
                         delim = ","),silent = TRUE
    )
  }

  for (name in names(results$CorrPlot)){
    try(
      ggplot2::ggsave(paste0(OutPath,'/StatCorr/',name,".png"),
                      plot = results$CorrPlot[[name]],
                      width =  results$CorrPlot_para[[name]][['width']],
                      height = results$CorrPlot_para[[name]][['height']],
                      units = "cm"),silent = TRUE
    )
  }
  return(results)
}


#' @title End the analysis
#' @description End the analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by InitStat.
#' @return Exit status
#' @export
#' @examples res = InitStat()
#'    res1 = LoadStat(PID = res$PID, UseExample = "example#1")
#'    res2 = StatCorr(PID = res$PID, Group = T, VarsX = "X5,X6,X7,X8,X9", VarsY = "Y1", VarsBy = "Y1", Method = "pearson", Layout = "bubble", Brightness = "dark", Palette = "nature")
#'    res3 = FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}
