
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoDB module
#' @description Initialize ExpoDB module analysis. It can generate an R6 class object.
#' @usage InitDb()
#' @param 
#' @details ExpoDB module is designed as a convenient tool to explore the data, 
#'     as well as facilitating to find the biological relationship between exposure 
#'     and diseases from the perspective of bioinformatics. This module adopts 
#'     the most frequently-used and authoritative databases, 
#'     e.g., T3DB, CTD, ToxCast, StringDB, STITCH, KEGG, and GO.
#' @return An R6 class object.
#' @export
#' @examples res <- InitDb()
#'     FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

InitDb = function(){
  url = paste0(urlhead,'InitDb')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Load data file for ExpoDB module
#' @description Load data file for ExpoDB module
#' @usage LoadDb(PID, UseExample = "default", DataPath=NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoDB
#' @param UseExample chr. Method of uploading data. If "default"，user should upload their own data files, 
#'    or use "example#1" provided by this module. 
#' @param DataPath chr. Input directory of data file, e.g. "D:/test/eg_data_biolink.xlsx". It should be 
#'    noted that the slash symbol is "/", not "\".
#' @details 
#' @return An R6 class object containing the input data.
#' @export
#' @examples res <- InitDb()
#'    res1 = LoadDb(PID = res$PID, UseExample = "example#1")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang 

LoadDb =function(PID,
                 UseExample="default",
                 DataPath=NULL){
  url = paste0(urlhead,'LoadDb')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)
  }else{
    exdata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID=PID,
                                         UseExample=UseExample,
                                         Expodata=exdata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Explain the abbreviations
#' @description Explain the abbreviations in ExposomeX platform
#' @usage ExpoAbbr(PID, OutPath = "default", Keys)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoDB
#' @param Keys chr. Any keywords to search. "default" means using the values .
#'     in the input data file. Users can also enter the keywords here. It should be 
#'     noted that there is fixed format for the entering characters separated 
#'     with comma and without space, e.g., "EpiDesign,Cros,Cohort".
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @details 
#' @return A data frame
#' @export
#' @examples res <- InitDb()
#'    res1 = LoadDb(PID = res$PID, UseExample = "example#1")
#'    res2 = ExpoAbbr(PID=res$PID,OutPath = OutPath,Keys = "default")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang 

ExpoAbbr = function(PID,
                    OutPath = "default",
                    Keys){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'ExpoAbbr')
  res = httr::POST(url,
                   body = list(PID=PID,
                               Keys=Keys),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/Abbr'))
  try(
    vroom::vroom_write(results$AbbrTable,
                       paste0(OutPath,'/Abbr/abbr.csv'), delim = ","),
    silent = TRUE
  )
  return(results$AbbrTable)
}


#' @title Explain keywords
#' @description Explain the keyword in ExposomeX platform
#' @usage ExpoDict(PID, OutPath = "default", Class, Keys)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoDB
#' @param Class chr. Choose the search range of the concerned keywords. Options include 
#'     "chemical" (Some exposure factors may be a mixture of chemicals, e.g. PM2.5, 
#'     tobacco smoking. As chemicals account for the majority, we use "Chemical" for convenience), 
#'     "metabolite" (the chemicals used for metabolome analysis in the KEGG database), 
#'     "protein", "enzyme" (referring in particular to the enzymes in the KEGG database), 
#'     "disease", "GO" (gene ontology), and "ion.adduct" (the ion adducts in the 
#'     liquid chromatograph-mass spectrometry).
#' @param Keys chr. Any keywords to search. "default" means using the values in the 
#'     input data file. Users can also enter the keywords here. It should be noted that 
#'     there is fixed format for the entering characters separated with comma and without space, 
#'     e.g., "7440-43-9,OMIM:619217,zinc,GO:0010942".
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @details 
#' @return A data frame
#' @export
#' @examples res <- InitDb()
#'    res1 = LoadDb(PID = res$PID, UseExample = "example#1")
#'    res2 = ExpoDict(PID=res$PID,OutPath = OutPath,Class = "GO",Keys = "default")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang 

ExpoDict = function(PID,
                    OutPath = "default",
                    Class,
                    Keys){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'ExpoDict')
  res = httr::POST(url,
                   body = list(PID=PID,
                               Class=Class,
                               Keys= Keys),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/Dict'))
  try(
    vroom::vroom_write(results$DictTable,
                       paste0(OutPath,'/Dict/dict_',Class,".csv"), delim = ","),
    silent = TRUE
  )
  return(results$DictTable)
}


#' @title Convert keywords
#' @description Convert the keywords from different sources in ExposomeX platform.
#' @usage ExpoConv = function(PID, OutPath = "default", From, To, Keys)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoDB
#' @param From chr. Choose the search range of the convert direction for the concerned keywords (from -> to).
#'     Options include "chemical" <-> "cas.rn" (Chemical name <-> CAS Registry Number), 
#'     "inchikey" <-> "chemical" (InChIKey <-> Chemical name), 
#'     "metabolite" <-> "kegg.entry" (Metabolite name <-> InChIKey), 
#'     "kegg.entry" <-> "metabolite" (KEGG Entry ID <-> Metabolite name), 
#'     "protein" <-> "uniprot" (protein name <-> UniProt ID), 
#'     "uniprot" <-> "ensembl" (UniProt ID <-> Chemical name), 
#'     "enzyme" <-> "uniprot" (Enzyme name <-> UniProt ID), 
#'     "disease" <-> "disease.id" (Disease <-> Disease.id)
#' @param To chr. see "from".
#' @param Keys chr. Any keywords belong to the classes of "from" and "to" to search. 
#'     "default" means using the values in the input data file. Users can also enter 
#'     the keywords here. It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "7440-43-9,OMIM:619217,zinc,GO:0010942".
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @details 
#' @return A data frame
#' @export
#' @examples res <- InitDb()
#'    res1 = LoadDb(PID = res$PID, UseExample = "example#1")
#'    res2 = ExpoConv(PID=res$PID,OutPath = OutPath,From = "chemical",To = "cas.rn",Keys = "default")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang 

ExpoConv = function(PID,
                    OutPath = "default",
                    From,
                    To,
                    Keys){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  message("It may take some time. Thanks for your patient waiting!")
  
  url = paste0(urlhead,'ExpoConv')
  res = httr::POST(url,
                   body = list(PID=PID,
                               From=From,
                               To=To,
                               Keys=Keys),
                   encode = 'json',
                   httr::timeout(600))
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/Conv'))
  try(
    vroom::vroom_write(results$ConvTable,
                       paste0(OutPath,'/Conv/conv_',From,"_to_",To,".csv"), delim = ","),
    silent = TRUE
  )
  return(results$ConvTable)
}


#' @title Find the nexuses between keywords
#' @description Find the nexuses between the keywords in ExposomeX platform. 
#'     Nexus direction from keywords A (class A) to keywords B (class B)
#' @usage ExpoNexus = function(PID, OutPath = "default", ClassA, ClassB, KeysA, KeysB)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoDB
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that 
#'     the slash symbol is "/", not "\". If "default", the current working directory will be set.
#' @param ClassA chr. Find the nexuses between the keywords in ClassA and ClassB.
#'     Options include "chemical" <-> "protein", "chemical" <-> "GO", 
#'     "protein" <-> "protein", "disease" <-> "GO", "protein" <-> "disease"
#' @param ClassB chr. See "ClassA".
#' @param KeysA chr. The lowercases of name, alias, and ID of chemical, metabolite, protein, 
#'     and enzyme are all accepted. e.g., "7440-43-9,OMIM:619217,zinc,GO:0010942".
#' @param KeysB chr. See "KeysA".
#' @details 
#' @return A data frame
#' @export
#' @examples res <- InitDb()
#'    res1 = LoadDb(PID = res$PID, UseExample = "example#1")
#'    res2 = ExpoNexus(PID=res$PID,OutPath = OutPath,ClassA = "chemical",
#'        ClassB = "protein",KeysA = "default",KeysB = "default")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang 

ExpoNexus = function(PID,
                     OutPath = "default",
                     ClassA,
                     ClassB,
                     KeysA,
                     KeysB){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  
  message("It may take some time. Thanks for your patient waiting!")
  
  url = paste0(urlhead,'ExpoNexus')
  res = httr::POST(url,
                   body = list(PID=PID,
                               ClassA =ClassA,
                               ClassB =ClassB,
                               KeysA =KeysA,
                               KeysB =KeysB
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/Nexus'))
  try(
    vroom::vroom_write(results$NexusTable,
                       paste0(OutPath,'/Nexus/nexus_',ClassA, "_to_", ClassB,".csv"), delim = ","),
    silent = TRUE
  )
  return(results$NexusTable)
}


#' @title Annotate the non-targeted features
#' @description Annotate the non-targeted features from high-resolution mass spectrometry
#' @usage ExpoAnno = function(PID, OutPath = "default", MassToCharge, AdductPos, 
#'     AdductNeg, Accuracy = 1)
#' @param PID chr. Program ID. It must be the same with the PID generated by ExpoDB
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param MassToCharge chr. Mass to charge ratio (m/z). It ranges 50-1000. If "default", 
#'     the values in the input data file are used. Users can also enter the keywords here. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "150,200,210".
#' @param AdductPos chr. Adducts collected in the positive mode. If "default", the values 
#'     in the input data file are chosen. Users can also enter the keywords here. 
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "M+H+Na,M+2ACN+2H,M+DMSO+H". 
#'     All the positive abducts are M+3ACN+2H,M+ACN+H,M+NH4,M+2ACN+2H,M+2H,M+3H,M+3Na,
#'     "M+2Na-H,M+ACN+Na,M+H+Na,M+2K-H,M+H+NH4,2M+K,M+K,2M+NH4,2M+Na,M+2Na,M+DMSO+H,
#'     M+2ACN+H,M+IsoProp+Na+H,M+2H+Na,M+ACN+2H,M+H,2M+H,M+CH3OH+H,M+H+2Na,M+Na",
#'     2M+ACN+H,2M+ACN+Na,M+IsoProp+H,M+H+K"
#' @param AdductNeg chr. Adducts collected in the negative mode. If "default", the values 
#'     in the input data file are chosen. Users can also enter the keywords here.
#'     It should be noted that there is fixed format for the entering characters 
#'     separated with comma and without space, e.g., "M+Hac-H,M-2H,M-H2O-H".
#'     All the negative abducts are "M+FA-H,M+Hac-H,M+Br,3M-H,2M+Hac-H,M+K-2H,2M+FA-H,
#'     M-H,M-H2O-H,M+Na-2H,M-2H,M+TFA-H,M+Cl,M-3H,2M-H".
#' @param Accuracy num. Upper limit of accuracy to match the target molecular.
#' @details 
#' @return A data frame
#' @export
#' @examples res <- InitDb()
#'    res1 = LoadDb(PID = res$PID, UseExample = "example#1")
#'    res6 = ExpoAnno(PID=res$PID,OutPath = OutPath,MassToCharge = "default",
#'    AdductPos = "all",AdductNeg = "all",Accuracy = 5)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang 

ExpoAnno = function(PID,
                    OutPath = "default",
                    MassToCharge,
                    AdductPos,
                    AdductNeg,
                    Accuracy = 1){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'ExpoAnno')
  res = httr::POST(url,
                   body = list(PID=PID,
                               MassToCharge =MassToCharge,
                               AdductPos =AdductPos,
                               AdductNeg =AdductNeg,
                               Accuracy =Accuracy
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/Anno'))
  try(
    vroom::vroom_write(results$AnnoTable,
                       paste0(OutPath,'/Anno/anno_',Accuracy,"ppm.csv"), delim = ","),
    silent = TRUE
  )
  return(results$AnnoTable)
}


#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by any initial functions.
#' @details 
#' @return Exit status
#' @export
#' @examples res = InitBioLink()
#'    res = LoadBioLink(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}


